/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type WebhookSyncFinishedWebhookPayloadRequest = {
  /**
   * HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
   */
  x_kombo_signature: string;
  body: models.SyncFinishedWebhookPayload;
};

/** @internal */
export const WebhookSyncFinishedWebhookPayloadRequest$inboundSchema: z.ZodType<
  WebhookSyncFinishedWebhookPayloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Kombo-Signature": z.string(),
  body: models.SyncFinishedWebhookPayload$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Kombo-Signature": "x_kombo_signature",
  });
});
/** @internal */
export type WebhookSyncFinishedWebhookPayloadRequest$Outbound = {
  "X-Kombo-Signature": string;
  body: models.SyncFinishedWebhookPayload$Outbound;
};

/** @internal */
export const WebhookSyncFinishedWebhookPayloadRequest$outboundSchema: z.ZodType<
  WebhookSyncFinishedWebhookPayloadRequest$Outbound,
  z.ZodTypeDef,
  WebhookSyncFinishedWebhookPayloadRequest
> = z.object({
  x_kombo_signature: z.string(),
  body: models.SyncFinishedWebhookPayload$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    x_kombo_signature: "X-Kombo-Signature",
  });
});

export function webhookSyncFinishedWebhookPayloadRequestToJSON(
  webhookSyncFinishedWebhookPayloadRequest:
    WebhookSyncFinishedWebhookPayloadRequest,
): string {
  return JSON.stringify(
    WebhookSyncFinishedWebhookPayloadRequest$outboundSchema.parse(
      webhookSyncFinishedWebhookPayloadRequest,
    ),
  );
}
export function webhookSyncFinishedWebhookPayloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  WebhookSyncFinishedWebhookPayloadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookSyncFinishedWebhookPayloadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WebhookSyncFinishedWebhookPayloadRequest' from JSON`,
  );
}
