/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { KomboCore } from "../core.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as webhooks from "../models/webhooks/index.js";
import { ERR, Result } from "../types/fp.js";

export async function validateWebhook(_client: KomboCore, {
  request: rawRequest,
}: {
  request: {
    body: BodyInit;
    method: string;
    url: string;
    headers: Record<string, string> | Headers;
  } | Request;
}): Promise<
  Result<
    | webhooks.WebhookDataChangedWebhookPayloadRequest
    | webhooks.WebhookConnectionFlowFailedWebhookPayloadRequest
    | webhooks.WebhookIntegrationCreatedWebhookPayloadRequest
    | webhooks.WebhookIntegrationDeletedWebhookPayloadRequest
    | webhooks.WebhookAssessmentOrderReceivedWebhookPayloadRequest
    | webhooks.WebhookInlineAssessmentOrderReceivedWebhookPayloadRequest
    | webhooks.WebhookIntegrationStateChangedWebhookPayloadRequest
    | webhooks.WebhookSyncFinishedWebhookPayloadRequest,
    SDKValidationError
  >
> {
  const request = normalizeRequest(rawRequest);
  const knownSchemas = [
    webhooks.webhookDataChangedWebhookPayloadRequestFromJSON,
    webhooks.webhookConnectionFlowFailedWebhookPayloadRequestFromJSON,
    webhooks.webhookIntegrationCreatedWebhookPayloadRequestFromJSON,
    webhooks.webhookIntegrationDeletedWebhookPayloadRequestFromJSON,
    webhooks.webhookAssessmentOrderReceivedWebhookPayloadRequestFromJSON,
    webhooks.webhookInlineAssessmentOrderReceivedWebhookPayloadRequestFromJSON,
    webhooks.webhookIntegrationStateChangedWebhookPayloadRequestFromJSON,
    webhooks.webhookSyncFinishedWebhookPayloadRequestFromJSON,
  ];

  const jsonString = await request.text();

  for (const schema of knownSchemas) {
    const ret = schema(jsonString);
    if (ret.ok) {
      return ret;
    }
  }

  return ERR(
    new SDKValidationError(
      "No matching schema found for the given webhook payload",
      jsonString,
      jsonString,
    ),
  );
}

function normalizeRequest(
  request: {
    body: BodyInit;
    method: string;
    url: string;
    headers: Record<string, string> | Headers;
  } | Request,
): Request {
  if (request instanceof Request) {
    return request;
  }
  return new Request(request.url, request);
}
