/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Assessment } from "./assessment.js";
import { Ats } from "./ats.js";
import { Connect } from "./connect.js";
import { General } from "./general.js";
import { Hris } from "./hris.js";

export class Kombo extends ClientSDK {
  private _general?: General;
  get general(): General {
    return (this._general ??= new General(this._options));
  }

  private _hris?: Hris;
  get hris(): Hris {
    return (this._hris ??= new Hris(this._options));
  }

  private _ats?: Ats;
  get ats(): Ats {
    return (this._ats ??= new Ats(this._options));
  }

  private _assessment?: Assessment;
  get assessment(): Assessment {
    return (this._assessment ??= new Assessment(this._options));
  }

  private _connect?: Connect;
  get connect(): Connect {
    return (this._connect ??= new Connect(this._options));
  }
}
