/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type DeleteIntegrationsIntegrationIdRequest = {
  /**
   * DELETE /integrations/:integration_id Parameter
   */
  integration_id: string;
  /**
   * DELETE /integrations/:integration_id Request body
   */
  body: models.DeleteIntegrationsIntegrationIdRequestBody;
};

/** @internal */
export type DeleteIntegrationsIntegrationIdRequest$Outbound = {
  integration_id: string;
  body: models.DeleteIntegrationsIntegrationIdRequestBody$Outbound;
};

/** @internal */
export const DeleteIntegrationsIntegrationIdRequest$outboundSchema: z.ZodType<
  DeleteIntegrationsIntegrationIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteIntegrationsIntegrationIdRequest
> = z.object({
  integration_id: z.string(),
  body: models.DeleteIntegrationsIntegrationIdRequestBody$outboundSchema,
});

export function deleteIntegrationsIntegrationIdRequestToJSON(
  deleteIntegrationsIntegrationIdRequest:
    DeleteIntegrationsIntegrationIdRequest,
): string {
  return JSON.stringify(
    DeleteIntegrationsIntegrationIdRequest$outboundSchema.parse(
      deleteIntegrationsIntegrationIdRequest,
    ),
  );
}
