/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAtsApplicationStagesGlobals = {
  /**
   * ID of the integration you want to interact with.
   */
  integration_id?: string | undefined;
};

export type GetAtsApplicationStagesRequest = {
  /**
   * An optional cursor string used for pagination. This can be retrieved from the `next` property of the previous page response.
   */
  cursor?: string | undefined;
  /**
   * The number of results to return per page. Maximum is 250.
   */
  page_size?: number | undefined;
  /**
   * Filter the entries based on the modification date in format YYYY-MM-DDTHH:mm:ss.sssZ. Returns records where either the record itself OR its nested data has been updated since this timestamp, even if the record's own `changed_at` field remains unchanged. If you want to track entry deletion, also set the `include_deleted=true` query parameter, because otherwise, deleted entries will be hidden. For more details, see [Understanding changed_at vs updated_after Behavior](https://docs.kombo.dev/ats/getting-started/fetching-data#understanding-changed_at-vs-updated_after-behavior).
   */
  updated_after?: Date | undefined;
  /**
   * By default, deleted entries are not returned. Use the `include_deleted` query param to include deleted entries too.
   */
  include_deleted?: boolean | undefined;
  /**
   * Filter by a comma-separated list of IDs such as `222k7eCGyUdgt2JWZDNnkDs3,B5DVmypWENfU6eMe6gYDyJG3`.
   */
  ids?: Array<string> | undefined;
  /**
   * Filter by a comma-separated list of remote IDs.
   */
  remote_ids?: Array<string> | undefined;
};

export type GetAtsApplicationStagesResponse = {
  result: models.GetAtsApplicationStagesPositiveResponse;
};

/** @internal */
export const GetAtsApplicationStagesGlobals$inboundSchema: z.ZodType<
  GetAtsApplicationStagesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  integration_id: z.string().optional(),
});

/** @internal */
export type GetAtsApplicationStagesGlobals$Outbound = {
  integration_id?: string | undefined;
};

/** @internal */
export const GetAtsApplicationStagesGlobals$outboundSchema: z.ZodType<
  GetAtsApplicationStagesGlobals$Outbound,
  z.ZodTypeDef,
  GetAtsApplicationStagesGlobals
> = z.object({
  integration_id: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAtsApplicationStagesGlobals$ {
  /** @deprecated use `GetAtsApplicationStagesGlobals$inboundSchema` instead. */
  export const inboundSchema = GetAtsApplicationStagesGlobals$inboundSchema;
  /** @deprecated use `GetAtsApplicationStagesGlobals$outboundSchema` instead. */
  export const outboundSchema = GetAtsApplicationStagesGlobals$outboundSchema;
  /** @deprecated use `GetAtsApplicationStagesGlobals$Outbound` instead. */
  export type Outbound = GetAtsApplicationStagesGlobals$Outbound;
}

export function getAtsApplicationStagesGlobalsToJSON(
  getAtsApplicationStagesGlobals: GetAtsApplicationStagesGlobals,
): string {
  return JSON.stringify(
    GetAtsApplicationStagesGlobals$outboundSchema.parse(
      getAtsApplicationStagesGlobals,
    ),
  );
}

export function getAtsApplicationStagesGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetAtsApplicationStagesGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAtsApplicationStagesGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAtsApplicationStagesGlobals' from JSON`,
  );
}

/** @internal */
export const GetAtsApplicationStagesRequest$inboundSchema: z.ZodType<
  GetAtsApplicationStagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  page_size: z.number().int().default(100),
  updated_after: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  include_deleted: z.boolean().default(false),
  ids: z.array(z.string()).optional(),
  remote_ids: z.array(z.string()).optional(),
});

/** @internal */
export type GetAtsApplicationStagesRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
  updated_after?: string | undefined;
  include_deleted: boolean;
  ids?: Array<string> | undefined;
  remote_ids?: Array<string> | undefined;
};

/** @internal */
export const GetAtsApplicationStagesRequest$outboundSchema: z.ZodType<
  GetAtsApplicationStagesRequest$Outbound,
  z.ZodTypeDef,
  GetAtsApplicationStagesRequest
> = z.object({
  cursor: z.string().optional(),
  page_size: z.number().int().default(100),
  updated_after: z.date().transform(v => v.toISOString()).optional(),
  include_deleted: z.boolean().default(false),
  ids: z.array(z.string()).optional(),
  remote_ids: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAtsApplicationStagesRequest$ {
  /** @deprecated use `GetAtsApplicationStagesRequest$inboundSchema` instead. */
  export const inboundSchema = GetAtsApplicationStagesRequest$inboundSchema;
  /** @deprecated use `GetAtsApplicationStagesRequest$outboundSchema` instead. */
  export const outboundSchema = GetAtsApplicationStagesRequest$outboundSchema;
  /** @deprecated use `GetAtsApplicationStagesRequest$Outbound` instead. */
  export type Outbound = GetAtsApplicationStagesRequest$Outbound;
}

export function getAtsApplicationStagesRequestToJSON(
  getAtsApplicationStagesRequest: GetAtsApplicationStagesRequest,
): string {
  return JSON.stringify(
    GetAtsApplicationStagesRequest$outboundSchema.parse(
      getAtsApplicationStagesRequest,
    ),
  );
}

export function getAtsApplicationStagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAtsApplicationStagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAtsApplicationStagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAtsApplicationStagesRequest' from JSON`,
  );
}

/** @internal */
export const GetAtsApplicationStagesResponse$inboundSchema: z.ZodType<
  GetAtsApplicationStagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.GetAtsApplicationStagesPositiveResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type GetAtsApplicationStagesResponse$Outbound = {
  Result: models.GetAtsApplicationStagesPositiveResponse$Outbound;
};

/** @internal */
export const GetAtsApplicationStagesResponse$outboundSchema: z.ZodType<
  GetAtsApplicationStagesResponse$Outbound,
  z.ZodTypeDef,
  GetAtsApplicationStagesResponse
> = z.object({
  result: models.GetAtsApplicationStagesPositiveResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAtsApplicationStagesResponse$ {
  /** @deprecated use `GetAtsApplicationStagesResponse$inboundSchema` instead. */
  export const inboundSchema = GetAtsApplicationStagesResponse$inboundSchema;
  /** @deprecated use `GetAtsApplicationStagesResponse$outboundSchema` instead. */
  export const outboundSchema = GetAtsApplicationStagesResponse$outboundSchema;
  /** @deprecated use `GetAtsApplicationStagesResponse$Outbound` instead. */
  export type Outbound = GetAtsApplicationStagesResponse$Outbound;
}

export function getAtsApplicationStagesResponseToJSON(
  getAtsApplicationStagesResponse: GetAtsApplicationStagesResponse,
): string {
  return JSON.stringify(
    GetAtsApplicationStagesResponse$outboundSchema.parse(
      getAtsApplicationStagesResponse,
    ),
  );
}

export function getAtsApplicationStagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAtsApplicationStagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAtsApplicationStagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAtsApplicationStagesResponse' from JSON`,
  );
}
