/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAtsOffersGlobals = {
  /**
   * ID of the integration you want to interact with.
   */
  integration_id?: string | undefined;
};

export type GetAtsOffersRequest = {
  /**
   * An optional cursor string used for pagination. This can be retrieved from the `next` property of the previous page response.
   */
  cursor?: string | undefined;
  /**
   * The number of results to return per page. Maximum is 250.
   */
  page_size?: number | undefined;
  /**
   * Filter the entries based on the modification date in format YYYY-MM-DDTHH:mm:ss.sssZ. Returns records where either the record itself OR its nested data has been updated since this timestamp, even if the record's own `changed_at` field remains unchanged. If you want to track entry deletion, also set the `include_deleted=true` query parameter, because otherwise, deleted entries will be hidden. For more details, see [Understanding changed_at vs updated_after Behavior](https://docs.kombo.dev/ats/getting-started/fetching-data#understanding-changed_at-vs-updated_after-behavior).
   */
  updated_after?: Date | undefined;
  /**
   * By default, deleted entries are not returned. Use the `include_deleted` query param to include deleted entries too.
   */
  include_deleted?: boolean | undefined;
  /**
   * Filter by a comma-separated list of IDs such as `222k7eCGyUdgt2JWZDNnkDs3,B5DVmypWENfU6eMe6gYDyJG3`.
   */
  ids?: Array<string> | undefined;
  /**
   * Filter by a comma-separated list of remote IDs.
   */
  remote_ids?: Array<string> | undefined;
};

export type GetAtsOffersResponse = {
  result: models.GetAtsOffersPositiveResponse;
};

/** @internal */
export const GetAtsOffersGlobals$inboundSchema: z.ZodType<
  GetAtsOffersGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  integration_id: z.string().optional(),
});

/** @internal */
export type GetAtsOffersGlobals$Outbound = {
  integration_id?: string | undefined;
};

/** @internal */
export const GetAtsOffersGlobals$outboundSchema: z.ZodType<
  GetAtsOffersGlobals$Outbound,
  z.ZodTypeDef,
  GetAtsOffersGlobals
> = z.object({
  integration_id: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAtsOffersGlobals$ {
  /** @deprecated use `GetAtsOffersGlobals$inboundSchema` instead. */
  export const inboundSchema = GetAtsOffersGlobals$inboundSchema;
  /** @deprecated use `GetAtsOffersGlobals$outboundSchema` instead. */
  export const outboundSchema = GetAtsOffersGlobals$outboundSchema;
  /** @deprecated use `GetAtsOffersGlobals$Outbound` instead. */
  export type Outbound = GetAtsOffersGlobals$Outbound;
}

export function getAtsOffersGlobalsToJSON(
  getAtsOffersGlobals: GetAtsOffersGlobals,
): string {
  return JSON.stringify(
    GetAtsOffersGlobals$outboundSchema.parse(getAtsOffersGlobals),
  );
}

export function getAtsOffersGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetAtsOffersGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAtsOffersGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAtsOffersGlobals' from JSON`,
  );
}

/** @internal */
export const GetAtsOffersRequest$inboundSchema: z.ZodType<
  GetAtsOffersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  page_size: z.number().int().default(100),
  updated_after: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  include_deleted: z.boolean().default(false),
  ids: z.array(z.string()).optional(),
  remote_ids: z.array(z.string()).optional(),
});

/** @internal */
export type GetAtsOffersRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
  updated_after?: string | undefined;
  include_deleted: boolean;
  ids?: Array<string> | undefined;
  remote_ids?: Array<string> | undefined;
};

/** @internal */
export const GetAtsOffersRequest$outboundSchema: z.ZodType<
  GetAtsOffersRequest$Outbound,
  z.ZodTypeDef,
  GetAtsOffersRequest
> = z.object({
  cursor: z.string().optional(),
  page_size: z.number().int().default(100),
  updated_after: z.date().transform(v => v.toISOString()).optional(),
  include_deleted: z.boolean().default(false),
  ids: z.array(z.string()).optional(),
  remote_ids: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAtsOffersRequest$ {
  /** @deprecated use `GetAtsOffersRequest$inboundSchema` instead. */
  export const inboundSchema = GetAtsOffersRequest$inboundSchema;
  /** @deprecated use `GetAtsOffersRequest$outboundSchema` instead. */
  export const outboundSchema = GetAtsOffersRequest$outboundSchema;
  /** @deprecated use `GetAtsOffersRequest$Outbound` instead. */
  export type Outbound = GetAtsOffersRequest$Outbound;
}

export function getAtsOffersRequestToJSON(
  getAtsOffersRequest: GetAtsOffersRequest,
): string {
  return JSON.stringify(
    GetAtsOffersRequest$outboundSchema.parse(getAtsOffersRequest),
  );
}

export function getAtsOffersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAtsOffersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAtsOffersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAtsOffersRequest' from JSON`,
  );
}

/** @internal */
export const GetAtsOffersResponse$inboundSchema: z.ZodType<
  GetAtsOffersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.GetAtsOffersPositiveResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type GetAtsOffersResponse$Outbound = {
  Result: models.GetAtsOffersPositiveResponse$Outbound;
};

/** @internal */
export const GetAtsOffersResponse$outboundSchema: z.ZodType<
  GetAtsOffersResponse$Outbound,
  z.ZodTypeDef,
  GetAtsOffersResponse
> = z.object({
  result: models.GetAtsOffersPositiveResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAtsOffersResponse$ {
  /** @deprecated use `GetAtsOffersResponse$inboundSchema` instead. */
  export const inboundSchema = GetAtsOffersResponse$inboundSchema;
  /** @deprecated use `GetAtsOffersResponse$outboundSchema` instead. */
  export const outboundSchema = GetAtsOffersResponse$outboundSchema;
  /** @deprecated use `GetAtsOffersResponse$Outbound` instead. */
  export type Outbound = GetAtsOffersResponse$Outbound;
}

export function getAtsOffersResponseToJSON(
  getAtsOffersResponse: GetAtsOffersResponse,
): string {
  return JSON.stringify(
    GetAtsOffersResponse$outboundSchema.parse(getAtsOffersResponse),
  );
}

export function getAtsOffersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAtsOffersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAtsOffersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAtsOffersResponse' from JSON`,
  );
}
