/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetConnectIntegrationByTokenTokenRequest = {
  /**
   * GET /connect/integration-by-token/:token Parameter
   */
  token: string;
};

/** @internal */
export const GetConnectIntegrationByTokenTokenRequest$inboundSchema: z.ZodType<
  GetConnectIntegrationByTokenTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string(),
});

/** @internal */
export type GetConnectIntegrationByTokenTokenRequest$Outbound = {
  token: string;
};

/** @internal */
export const GetConnectIntegrationByTokenTokenRequest$outboundSchema: z.ZodType<
  GetConnectIntegrationByTokenTokenRequest$Outbound,
  z.ZodTypeDef,
  GetConnectIntegrationByTokenTokenRequest
> = z.object({
  token: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetConnectIntegrationByTokenTokenRequest$ {
  /** @deprecated use `GetConnectIntegrationByTokenTokenRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetConnectIntegrationByTokenTokenRequest$inboundSchema;
  /** @deprecated use `GetConnectIntegrationByTokenTokenRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetConnectIntegrationByTokenTokenRequest$outboundSchema;
  /** @deprecated use `GetConnectIntegrationByTokenTokenRequest$Outbound` instead. */
  export type Outbound = GetConnectIntegrationByTokenTokenRequest$Outbound;
}

export function getConnectIntegrationByTokenTokenRequestToJSON(
  getConnectIntegrationByTokenTokenRequest:
    GetConnectIntegrationByTokenTokenRequest,
): string {
  return JSON.stringify(
    GetConnectIntegrationByTokenTokenRequest$outboundSchema.parse(
      getConnectIntegrationByTokenTokenRequest,
    ),
  );
}

export function getConnectIntegrationByTokenTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetConnectIntegrationByTokenTokenRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetConnectIntegrationByTokenTokenRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetConnectIntegrationByTokenTokenRequest' from JSON`,
  );
}
