/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetConnectIntegrationByTokenTokenRequest = {
  /**
   * GET /connect/integration-by-token/:token Parameter
   */
  token: string;
};

/** @internal */
export type GetConnectIntegrationByTokenTokenRequest$Outbound = {
  token: string;
};

/** @internal */
export const GetConnectIntegrationByTokenTokenRequest$outboundSchema: z.ZodType<
  GetConnectIntegrationByTokenTokenRequest$Outbound,
  z.ZodTypeDef,
  GetConnectIntegrationByTokenTokenRequest
> = z.object({
  token: z.string(),
});

export function getConnectIntegrationByTokenTokenRequestToJSON(
  getConnectIntegrationByTokenTokenRequest:
    GetConnectIntegrationByTokenTokenRequest,
): string {
  return JSON.stringify(
    GetConnectIntegrationByTokenTokenRequest$outboundSchema.parse(
      getConnectIntegrationByTokenTokenRequest,
    ),
  );
}
