/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetHrisPerformanceReviewsGlobals = {
  /**
   * ID of the integration you want to interact with.
   */
  integration_id?: string | undefined;
};

export type GetHrisPerformanceReviewsRequest = {
  /**
   * An optional cursor string used for pagination. This can be retrieved from the `next` property of the previous page response.
   */
  cursor?: string | undefined;
  /**
   * The number of results to return per page. Maximum is 250.
   */
  page_size?: number | undefined;
  /**
   * Filter the entries based on the modification date in format `YYYY-MM-DDTHH:mm:ss.sssZ`. Returns records where either the record itself **OR** its nested data has been updated since this timestamp, even if the record's own `changed_at` field remains unchanged.
   *
   * @remarks
   *
   * If you want to track entry deletion, also set the `include_deleted=true` query parameter, because otherwise, deleted entries will be hidden.
   *
   * For more details, see [Understanding changed_at vs updated_after Behavior](https://docs.kombo.dev/ats/getting-started/fetching-data#understanding-changed_at-vs-updated_after-behavior).
   */
  updated_after?: Date | undefined;
  /**
   * By default, deleted entries are not returned. Use the `include_deleted` query param to include deleted entries too.
   */
  include_deleted?: boolean | undefined;
  /**
   * Filter by a comma-separated list of IDs such as `222k7eCGyUdgt2JWZDNnkDs3,B5DVmypWENfU6eMe6gYDyJG3`.
   */
  ids?: Array<string> | undefined;
  /**
   * Filter by a comma-separated list of remote IDs.
   */
  remote_ids?: Array<string> | undefined;
  /**
   * Filter by a comma-separated list of `MANAGER`, `DIRECT_REPORT`, `PEER`, `SELF`
   *
   * @remarks
   *
   * Leave this blank to get results matching all values.
   */
  types?: Array<string> | undefined;
  /**
   * Filter by a comma-separated list of review cycle IDs.
   */
  review_cycle_ids?: Array<string> | undefined;
  /**
   * Filter by a comma-separated list of reviewee IDs.
   */
  reviewee_ids?: Array<string> | undefined;
};

export type GetHrisPerformanceReviewsResponse = {
  result: models.GetHrisPerformanceReviewsPositiveResponse;
};

/** @internal */
export type GetHrisPerformanceReviewsRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
  updated_after?: string | undefined;
  include_deleted: boolean;
  ids?: Array<string> | undefined;
  remote_ids?: Array<string> | undefined;
  types?: Array<string> | undefined;
  review_cycle_ids?: Array<string> | undefined;
  reviewee_ids?: Array<string> | undefined;
};

/** @internal */
export const GetHrisPerformanceReviewsRequest$outboundSchema: z.ZodType<
  GetHrisPerformanceReviewsRequest$Outbound,
  z.ZodTypeDef,
  GetHrisPerformanceReviewsRequest
> = z.object({
  cursor: z.string().optional(),
  page_size: z.number().int().default(100),
  updated_after: z.date().transform(v => v.toISOString()).optional(),
  include_deleted: z.boolean().default(false),
  ids: z.array(z.string()).optional(),
  remote_ids: z.array(z.string()).optional(),
  types: z.array(z.string()).optional(),
  review_cycle_ids: z.array(z.string()).optional(),
  reviewee_ids: z.array(z.string()).optional(),
});

export function getHrisPerformanceReviewsRequestToJSON(
  getHrisPerformanceReviewsRequest: GetHrisPerformanceReviewsRequest,
): string {
  return JSON.stringify(
    GetHrisPerformanceReviewsRequest$outboundSchema.parse(
      getHrisPerformanceReviewsRequest,
    ),
  );
}

/** @internal */
export const GetHrisPerformanceReviewsResponse$inboundSchema: z.ZodType<
  GetHrisPerformanceReviewsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.GetHrisPerformanceReviewsPositiveResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function getHrisPerformanceReviewsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisPerformanceReviewsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHrisPerformanceReviewsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisPerformanceReviewsResponse' from JSON`,
  );
}
