/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetIntegrationsIntegrationIdCustomFieldsRequest = {
  /**
   * GET /integrations/:integration_id/custom-fields Parameter
   */
  integration_id: string;
  /**
   * An optional cursor string used for pagination. This can be retrieved from the `next` property of the previous page response.
   */
  cursor?: string | undefined;
  /**
   * The number of results to return per page. Maximum is 250.
   */
  page_size?: number | undefined;
};

export type GetIntegrationsIntegrationIdCustomFieldsResponse = {
  result: models.GetIntegrationsIntegrationIdCustomFieldsPositiveResponse;
};

/** @internal */
export const GetIntegrationsIntegrationIdCustomFieldsRequest$inboundSchema:
  z.ZodType<
    GetIntegrationsIntegrationIdCustomFieldsRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    integration_id: z.string(),
    cursor: z.string().optional(),
    page_size: z.number().int().default(100),
  });

/** @internal */
export type GetIntegrationsIntegrationIdCustomFieldsRequest$Outbound = {
  integration_id: string;
  cursor?: string | undefined;
  page_size: number;
};

/** @internal */
export const GetIntegrationsIntegrationIdCustomFieldsRequest$outboundSchema:
  z.ZodType<
    GetIntegrationsIntegrationIdCustomFieldsRequest$Outbound,
    z.ZodTypeDef,
    GetIntegrationsIntegrationIdCustomFieldsRequest
  > = z.object({
    integration_id: z.string(),
    cursor: z.string().optional(),
    page_size: z.number().int().default(100),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIntegrationsIntegrationIdCustomFieldsRequest$ {
  /** @deprecated use `GetIntegrationsIntegrationIdCustomFieldsRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetIntegrationsIntegrationIdCustomFieldsRequest$inboundSchema;
  /** @deprecated use `GetIntegrationsIntegrationIdCustomFieldsRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetIntegrationsIntegrationIdCustomFieldsRequest$outboundSchema;
  /** @deprecated use `GetIntegrationsIntegrationIdCustomFieldsRequest$Outbound` instead. */
  export type Outbound =
    GetIntegrationsIntegrationIdCustomFieldsRequest$Outbound;
}

export function getIntegrationsIntegrationIdCustomFieldsRequestToJSON(
  getIntegrationsIntegrationIdCustomFieldsRequest:
    GetIntegrationsIntegrationIdCustomFieldsRequest,
): string {
  return JSON.stringify(
    GetIntegrationsIntegrationIdCustomFieldsRequest$outboundSchema.parse(
      getIntegrationsIntegrationIdCustomFieldsRequest,
    ),
  );
}

export function getIntegrationsIntegrationIdCustomFieldsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetIntegrationsIntegrationIdCustomFieldsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetIntegrationsIntegrationIdCustomFieldsRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetIntegrationsIntegrationIdCustomFieldsRequest' from JSON`,
  );
}

/** @internal */
export const GetIntegrationsIntegrationIdCustomFieldsResponse$inboundSchema:
  z.ZodType<
    GetIntegrationsIntegrationIdCustomFieldsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Result:
      models
        .GetIntegrationsIntegrationIdCustomFieldsPositiveResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  });

/** @internal */
export type GetIntegrationsIntegrationIdCustomFieldsResponse$Outbound = {
  Result:
    models.GetIntegrationsIntegrationIdCustomFieldsPositiveResponse$Outbound;
};

/** @internal */
export const GetIntegrationsIntegrationIdCustomFieldsResponse$outboundSchema:
  z.ZodType<
    GetIntegrationsIntegrationIdCustomFieldsResponse$Outbound,
    z.ZodTypeDef,
    GetIntegrationsIntegrationIdCustomFieldsResponse
  > = z.object({
    result:
      models
        .GetIntegrationsIntegrationIdCustomFieldsPositiveResponse$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIntegrationsIntegrationIdCustomFieldsResponse$ {
  /** @deprecated use `GetIntegrationsIntegrationIdCustomFieldsResponse$inboundSchema` instead. */
  export const inboundSchema =
    GetIntegrationsIntegrationIdCustomFieldsResponse$inboundSchema;
  /** @deprecated use `GetIntegrationsIntegrationIdCustomFieldsResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetIntegrationsIntegrationIdCustomFieldsResponse$outboundSchema;
  /** @deprecated use `GetIntegrationsIntegrationIdCustomFieldsResponse$Outbound` instead. */
  export type Outbound =
    GetIntegrationsIntegrationIdCustomFieldsResponse$Outbound;
}

export function getIntegrationsIntegrationIdCustomFieldsResponseToJSON(
  getIntegrationsIntegrationIdCustomFieldsResponse:
    GetIntegrationsIntegrationIdCustomFieldsResponse,
): string {
  return JSON.stringify(
    GetIntegrationsIntegrationIdCustomFieldsResponse$outboundSchema.parse(
      getIntegrationsIntegrationIdCustomFieldsResponse,
    ),
  );
}

export function getIntegrationsIntegrationIdCustomFieldsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetIntegrationsIntegrationIdCustomFieldsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetIntegrationsIntegrationIdCustomFieldsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetIntegrationsIntegrationIdCustomFieldsResponse' from JSON`,
  );
}
