/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetIntegrationsIntegrationIdRequest = {
  /**
   * GET /integrations/:integration_id Parameter
   */
  integration_id: string;
};

/** @internal */
export const GetIntegrationsIntegrationIdRequest$inboundSchema: z.ZodType<
  GetIntegrationsIntegrationIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  integration_id: z.string(),
});

/** @internal */
export type GetIntegrationsIntegrationIdRequest$Outbound = {
  integration_id: string;
};

/** @internal */
export const GetIntegrationsIntegrationIdRequest$outboundSchema: z.ZodType<
  GetIntegrationsIntegrationIdRequest$Outbound,
  z.ZodTypeDef,
  GetIntegrationsIntegrationIdRequest
> = z.object({
  integration_id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIntegrationsIntegrationIdRequest$ {
  /** @deprecated use `GetIntegrationsIntegrationIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetIntegrationsIntegrationIdRequest$inboundSchema;
  /** @deprecated use `GetIntegrationsIntegrationIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetIntegrationsIntegrationIdRequest$outboundSchema;
  /** @deprecated use `GetIntegrationsIntegrationIdRequest$Outbound` instead. */
  export type Outbound = GetIntegrationsIntegrationIdRequest$Outbound;
}

export function getIntegrationsIntegrationIdRequestToJSON(
  getIntegrationsIntegrationIdRequest: GetIntegrationsIntegrationIdRequest,
): string {
  return JSON.stringify(
    GetIntegrationsIntegrationIdRequest$outboundSchema.parse(
      getIntegrationsIntegrationIdRequest,
    ),
  );
}

export function getIntegrationsIntegrationIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetIntegrationsIntegrationIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetIntegrationsIntegrationIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIntegrationsIntegrationIdRequest' from JSON`,
  );
}
