/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest =
  {
    /**
     * PATCH /integrations/:integration_id/integration-fields/:integration_field_id Parameter
     */
    integration_id: string;
    /**
     * PATCH /integrations/:integration_id/integration-fields/:integration_field_id Parameter
     */
    integration_field_id: string;
    /**
     * PATCH /integrations/:integration_id/integration-fields/:integration_field_id Request body
     */
    body:
      models.PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequestBody;
  };

/** @internal */
export type PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest$Outbound =
  {
    integration_id: string;
    integration_field_id: string;
    body:
      models.PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequestBody$Outbound;
  };

/** @internal */
export const PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest$outboundSchema:
  z.ZodType<
    PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest$Outbound,
    z.ZodTypeDef,
    PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest
  > = z.object({
    integration_id: z.string(),
    integration_field_id: z.string(),
    body:
      models
        .PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequestBody$outboundSchema,
  });

export function patchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequestToJSON(
  patchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest:
    PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest,
): string {
  return JSON.stringify(
    PatchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest$outboundSchema
      .parse(
        patchIntegrationsIntegrationIdIntegrationFieldsIntegrationFieldIdRequest,
      ),
  );
}
