/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostForceSyncGlobals = {
  /**
   * ID of the integration you want to interact with.
   */
  integration_id?: string | undefined;
};

/** @internal */
export const PostForceSyncGlobals$inboundSchema: z.ZodType<
  PostForceSyncGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  integration_id: z.string().optional(),
});

/** @internal */
export type PostForceSyncGlobals$Outbound = {
  integration_id?: string | undefined;
};

/** @internal */
export const PostForceSyncGlobals$outboundSchema: z.ZodType<
  PostForceSyncGlobals$Outbound,
  z.ZodTypeDef,
  PostForceSyncGlobals
> = z.object({
  integration_id: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostForceSyncGlobals$ {
  /** @deprecated use `PostForceSyncGlobals$inboundSchema` instead. */
  export const inboundSchema = PostForceSyncGlobals$inboundSchema;
  /** @deprecated use `PostForceSyncGlobals$outboundSchema` instead. */
  export const outboundSchema = PostForceSyncGlobals$outboundSchema;
  /** @deprecated use `PostForceSyncGlobals$Outbound` instead. */
  export type Outbound = PostForceSyncGlobals$Outbound;
}

export function postForceSyncGlobalsToJSON(
  postForceSyncGlobals: PostForceSyncGlobals,
): string {
  return JSON.stringify(
    PostForceSyncGlobals$outboundSchema.parse(postForceSyncGlobals),
  );
}

export function postForceSyncGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<PostForceSyncGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostForceSyncGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostForceSyncGlobals' from JSON`,
  );
}
