/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostAtsCandidatesGlobals = {
  /**
   * ID of the integration you want to interact with.
   */
  integration_id?: string | undefined;
};

/** @internal */
export const PostAtsCandidatesGlobals$inboundSchema: z.ZodType<
  PostAtsCandidatesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  integration_id: z.string().optional(),
});

/** @internal */
export type PostAtsCandidatesGlobals$Outbound = {
  integration_id?: string | undefined;
};

/** @internal */
export const PostAtsCandidatesGlobals$outboundSchema: z.ZodType<
  PostAtsCandidatesGlobals$Outbound,
  z.ZodTypeDef,
  PostAtsCandidatesGlobals
> = z.object({
  integration_id: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesGlobals$ {
  /** @deprecated use `PostAtsCandidatesGlobals$inboundSchema` instead. */
  export const inboundSchema = PostAtsCandidatesGlobals$inboundSchema;
  /** @deprecated use `PostAtsCandidatesGlobals$outboundSchema` instead. */
  export const outboundSchema = PostAtsCandidatesGlobals$outboundSchema;
  /** @deprecated use `PostAtsCandidatesGlobals$Outbound` instead. */
  export type Outbound = PostAtsCandidatesGlobals$Outbound;
}

export function postAtsCandidatesGlobalsToJSON(
  postAtsCandidatesGlobals: PostAtsCandidatesGlobals,
): string {
  return JSON.stringify(
    PostAtsCandidatesGlobals$outboundSchema.parse(postAtsCandidatesGlobals),
  );
}

export function postAtsCandidatesGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<PostAtsCandidatesGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostAtsCandidatesGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesGlobals' from JSON`,
  );
}
