/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type PutIntegrationsIntegrationIdEnabledRequest = {
  /**
   * PUT /integrations/:integration_id/enabled Parameter
   */
  integration_id: string;
  /**
   * PUT /integrations/:integration_id/enabled Request body
   */
  body: models.PutIntegrationsIntegrationIdEnabledRequestBody;
};

/** @internal */
export type PutIntegrationsIntegrationIdEnabledRequest$Outbound = {
  integration_id: string;
  body: models.PutIntegrationsIntegrationIdEnabledRequestBody$Outbound;
};

/** @internal */
export const PutIntegrationsIntegrationIdEnabledRequest$outboundSchema:
  z.ZodType<
    PutIntegrationsIntegrationIdEnabledRequest$Outbound,
    z.ZodTypeDef,
    PutIntegrationsIntegrationIdEnabledRequest
  > = z.object({
    integration_id: z.string(),
    body: models.PutIntegrationsIntegrationIdEnabledRequestBody$outboundSchema,
  });

export function putIntegrationsIntegrationIdEnabledRequestToJSON(
  putIntegrationsIntegrationIdEnabledRequest:
    PutIntegrationsIntegrationIdEnabledRequest,
): string {
  return JSON.stringify(
    PutIntegrationsIntegrationIdEnabledRequest$outboundSchema.parse(
      putIntegrationsIntegrationIdEnabledRequest,
    ),
  );
}
