/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DeleteAtsCandidatesCandidateIdTagsPositiveResponseData = {};

export type DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning = {
  message: string;
};

export type DeleteAtsCandidatesCandidateIdTagsPositiveResponse = {
  status: "success";
  data: DeleteAtsCandidatesCandidateIdTagsPositiveResponseData;
  /**
   * These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
   */
  warnings: Array<DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning>;
};

/** @internal */
export const DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$inboundSchema:
  z.ZodType<
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$Outbound =
  {};

/** @internal */
export const DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$outboundSchema:
  z.ZodType<
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$Outbound,
    z.ZodTypeDef,
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$ {
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$inboundSchema` instead. */
  export const inboundSchema =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$inboundSchema;
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$outboundSchema` instead. */
  export const outboundSchema =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$outboundSchema;
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$Outbound` instead. */
  export type Outbound =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$Outbound;
}

export function deleteAtsCandidatesCandidateIdTagsPositiveResponseDataToJSON(
  deleteAtsCandidatesCandidateIdTagsPositiveResponseData:
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData,
): string {
  return JSON.stringify(
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$outboundSchema.parse(
      deleteAtsCandidatesCandidateIdTagsPositiveResponseData,
    ),
  );
}

export function deleteAtsCandidatesCandidateIdTagsPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteAtsCandidatesCandidateIdTagsPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteAtsCandidatesCandidateIdTagsPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$inboundSchema:
  z.ZodType<
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

/** @internal */
export type DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$Outbound =
  {
    message: string;
  };

/** @internal */
export const DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$outboundSchema:
  z.ZodType<
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$Outbound,
    z.ZodTypeDef,
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning
  > = z.object({
    message: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$ {
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$inboundSchema` instead. */
  export const inboundSchema =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$inboundSchema;
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$outboundSchema` instead. */
  export const outboundSchema =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$outboundSchema;
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$Outbound` instead. */
  export type Outbound =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$Outbound;
}

export function deleteAtsCandidatesCandidateIdTagsPositiveResponseWarningToJSON(
  deleteAtsCandidatesCandidateIdTagsPositiveResponseWarning:
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning,
): string {
  return JSON.stringify(
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$outboundSchema
      .parse(deleteAtsCandidatesCandidateIdTagsPositiveResponseWarning),
  );
}

export function deleteAtsCandidatesCandidateIdTagsPositiveResponseWarningFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning' from JSON`,
  );
}

/** @internal */
export const DeleteAtsCandidatesCandidateIdTagsPositiveResponse$inboundSchema:
  z.ZodType<
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$inboundSchema
    ),
    warnings: z.array(
      z.lazy(() =>
        DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$inboundSchema
      ),
    ),
  });

/** @internal */
export type DeleteAtsCandidatesCandidateIdTagsPositiveResponse$Outbound = {
  status: "success";
  data: DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$Outbound;
  warnings: Array<
    DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$Outbound
  >;
};

/** @internal */
export const DeleteAtsCandidatesCandidateIdTagsPositiveResponse$outboundSchema:
  z.ZodType<
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse$Outbound,
    z.ZodTypeDef,
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      DeleteAtsCandidatesCandidateIdTagsPositiveResponseData$outboundSchema
    ),
    warnings: z.array(
      z.lazy(() =>
        DeleteAtsCandidatesCandidateIdTagsPositiveResponseWarning$outboundSchema
      ),
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAtsCandidatesCandidateIdTagsPositiveResponse$ {
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponse$inboundSchema` instead. */
  export const inboundSchema =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse$inboundSchema;
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponse$outboundSchema` instead. */
  export const outboundSchema =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse$outboundSchema;
  /** @deprecated use `DeleteAtsCandidatesCandidateIdTagsPositiveResponse$Outbound` instead. */
  export type Outbound =
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse$Outbound;
}

export function deleteAtsCandidatesCandidateIdTagsPositiveResponseToJSON(
  deleteAtsCandidatesCandidateIdTagsPositiveResponse:
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse,
): string {
  return JSON.stringify(
    DeleteAtsCandidatesCandidateIdTagsPositiveResponse$outboundSchema.parse(
      deleteAtsCandidatesCandidateIdTagsPositiveResponse,
    ),
  );
}

export function deleteAtsCandidatesCandidateIdTagsPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteAtsCandidatesCandidateIdTagsPositiveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteAtsCandidatesCandidateIdTagsPositiveResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteAtsCandidatesCandidateIdTagsPositiveResponse' from JSON`,
  );
}
