/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DeleteIntegrationsIntegrationIdPositiveResponseData = {};

export type DeleteIntegrationsIntegrationIdPositiveResponse = {
  status: "success";
  data: DeleteIntegrationsIntegrationIdPositiveResponseData;
};

/** @internal */
export const DeleteIntegrationsIntegrationIdPositiveResponseData$inboundSchema:
  z.ZodType<
    DeleteIntegrationsIntegrationIdPositiveResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type DeleteIntegrationsIntegrationIdPositiveResponseData$Outbound = {};

/** @internal */
export const DeleteIntegrationsIntegrationIdPositiveResponseData$outboundSchema:
  z.ZodType<
    DeleteIntegrationsIntegrationIdPositiveResponseData$Outbound,
    z.ZodTypeDef,
    DeleteIntegrationsIntegrationIdPositiveResponseData
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteIntegrationsIntegrationIdPositiveResponseData$ {
  /** @deprecated use `DeleteIntegrationsIntegrationIdPositiveResponseData$inboundSchema` instead. */
  export const inboundSchema =
    DeleteIntegrationsIntegrationIdPositiveResponseData$inboundSchema;
  /** @deprecated use `DeleteIntegrationsIntegrationIdPositiveResponseData$outboundSchema` instead. */
  export const outboundSchema =
    DeleteIntegrationsIntegrationIdPositiveResponseData$outboundSchema;
  /** @deprecated use `DeleteIntegrationsIntegrationIdPositiveResponseData$Outbound` instead. */
  export type Outbound =
    DeleteIntegrationsIntegrationIdPositiveResponseData$Outbound;
}

export function deleteIntegrationsIntegrationIdPositiveResponseDataToJSON(
  deleteIntegrationsIntegrationIdPositiveResponseData:
    DeleteIntegrationsIntegrationIdPositiveResponseData,
): string {
  return JSON.stringify(
    DeleteIntegrationsIntegrationIdPositiveResponseData$outboundSchema.parse(
      deleteIntegrationsIntegrationIdPositiveResponseData,
    ),
  );
}

export function deleteIntegrationsIntegrationIdPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteIntegrationsIntegrationIdPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteIntegrationsIntegrationIdPositiveResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteIntegrationsIntegrationIdPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const DeleteIntegrationsIntegrationIdPositiveResponse$inboundSchema:
  z.ZodType<
    DeleteIntegrationsIntegrationIdPositiveResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      DeleteIntegrationsIntegrationIdPositiveResponseData$inboundSchema
    ),
  });

/** @internal */
export type DeleteIntegrationsIntegrationIdPositiveResponse$Outbound = {
  status: "success";
  data: DeleteIntegrationsIntegrationIdPositiveResponseData$Outbound;
};

/** @internal */
export const DeleteIntegrationsIntegrationIdPositiveResponse$outboundSchema:
  z.ZodType<
    DeleteIntegrationsIntegrationIdPositiveResponse$Outbound,
    z.ZodTypeDef,
    DeleteIntegrationsIntegrationIdPositiveResponse
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      DeleteIntegrationsIntegrationIdPositiveResponseData$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteIntegrationsIntegrationIdPositiveResponse$ {
  /** @deprecated use `DeleteIntegrationsIntegrationIdPositiveResponse$inboundSchema` instead. */
  export const inboundSchema =
    DeleteIntegrationsIntegrationIdPositiveResponse$inboundSchema;
  /** @deprecated use `DeleteIntegrationsIntegrationIdPositiveResponse$outboundSchema` instead. */
  export const outboundSchema =
    DeleteIntegrationsIntegrationIdPositiveResponse$outboundSchema;
  /** @deprecated use `DeleteIntegrationsIntegrationIdPositiveResponse$Outbound` instead. */
  export type Outbound =
    DeleteIntegrationsIntegrationIdPositiveResponse$Outbound;
}

export function deleteIntegrationsIntegrationIdPositiveResponseToJSON(
  deleteIntegrationsIntegrationIdPositiveResponse:
    DeleteIntegrationsIntegrationIdPositiveResponse,
): string {
  return JSON.stringify(
    DeleteIntegrationsIntegrationIdPositiveResponse$outboundSchema.parse(
      deleteIntegrationsIntegrationIdPositiveResponse,
    ),
  );
}

export function deleteIntegrationsIntegrationIdPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteIntegrationsIntegrationIdPositiveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteIntegrationsIntegrationIdPositiveResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteIntegrationsIntegrationIdPositiveResponse' from JSON`,
  );
}
