/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The current status of the assessment order.
 */
export const GetAssessmentOrdersPositiveResponseStatus = {
  Open: "OPEN",
  Completed: "COMPLETED",
  Cancelled: "CANCELLED",
  Rejected: "REJECTED",
} as const;
/**
 * The current status of the assessment order.
 */
export type GetAssessmentOrdersPositiveResponseStatus = ClosedEnum<
  typeof GetAssessmentOrdersPositiveResponseStatus
>;

/**
 * Information about the candidate taking the assessment.
 */
export type GetAssessmentOrdersPositiveResponseCandidate = {
  /**
   * The candidate's identifier in the integrated system.
   */
  remote_id: string | null;
  /**
   * The candidate's email address.
   */
  email: string;
  /**
   * The candidate's first name.
   */
  first_name: string | null;
  /**
   * The candidate's last name.
   */
  last_name: string | null;
  /**
   * The candidate's phone number.
   */
  phone: string | null;
};

/**
 * Information about the job application.
 */
export type GetAssessmentOrdersPositiveResponseApplication = {
  /**
   * The application's identifier in the integrated system.
   */
  remote_id: string | null;
};

/**
 * The job location information.
 */
export type GetAssessmentOrdersPositiveResponseLocation = {
  /**
   * If we can parse the address data, this field contains the first part of the street information.
   */
  street_1?: string | null | undefined;
  street_2?: string | null | undefined;
  city?: string | null | undefined;
  state?: string | null | undefined;
  zip_code?: string | null | undefined;
  /**
   * Contains the ISO2 country code if possible. If not, it contains the original value.
   */
  country?: string | null | undefined;
  /**
   * If we have address data, this is filled with the raw address string.
   */
  raw?: string | null | undefined;
};

export const GetAssessmentOrdersPositiveResponseHiringTeamRole = {
  Recruiter: "RECRUITER",
  HiringManager: "HIRING_MANAGER",
} as const;
export type GetAssessmentOrdersPositiveResponseHiringTeamRole = ClosedEnum<
  typeof GetAssessmentOrdersPositiveResponseHiringTeamRole
>;

/**
 * A member of the hiring team.
 */
export type GetAssessmentOrdersPositiveResponseHiringTeam = {
  /**
   * The team member's identifier in the integrated system.
   */
  remote_id: string | null;
  /**
   * The team member's email address.
   */
  email: string | null;
  /**
   * The team member's first name.
   */
  first_name: string | null;
  /**
   * The team member's last name.
   */
  last_name: string | null;
  /**
   * Array of the roles of the user for this specific job.
   */
  hiring_team_roles: Array<GetAssessmentOrdersPositiveResponseHiringTeamRole>;
};

/**
 * Information about the job posting.
 */
export type GetAssessmentOrdersPositiveResponseJob = {
  /**
   * The job's identifier in the integrated system.
   */
  remote_id: string | null;
  /**
   * The job title.
   */
  name: string | null;
  /**
   * The human readable job code. Some systems expose this as the Requisition Code/ID.
   */
  job_code: string | null;
  /**
   * Description of the job. This field is usually returned as HTML.
   */
  description: string | null;
  /**
   * The job location information.
   */
  location: GetAssessmentOrdersPositiveResponseLocation | null;
  /**
   * The hiring team allows you to provision users into your system who can access the job and its applications.
   */
  hiring_team: Array<GetAssessmentOrdersPositiveResponseHiringTeam>;
};

export type GetAssessmentOrdersPositiveResponseResult = {
  /**
   * The unique identifier of the assessment order.
   */
  id: string;
  /**
   * The identifier of the assessment package.
   */
  package_id: string;
  /**
   * The current status of the assessment order.
   */
  status: GetAssessmentOrdersPositiveResponseStatus;
  /**
   * Information about the candidate taking the assessment.
   */
  candidate: GetAssessmentOrdersPositiveResponseCandidate;
  /**
   * Information about the job application.
   */
  application: GetAssessmentOrdersPositiveResponseApplication;
  /**
   * Information about the job posting.
   */
  job: GetAssessmentOrdersPositiveResponseJob;
};

export type GetAssessmentOrdersPositiveResponseData = {
  next: string | null;
  results: Array<GetAssessmentOrdersPositiveResponseResult>;
};

export type GetAssessmentOrdersPositiveResponse = {
  status: "success";
  data: GetAssessmentOrdersPositiveResponseData;
};

/** @internal */
export const GetAssessmentOrdersPositiveResponseStatus$inboundSchema:
  z.ZodNativeEnum<typeof GetAssessmentOrdersPositiveResponseStatus> = z
    .nativeEnum(GetAssessmentOrdersPositiveResponseStatus);

/** @internal */
export const GetAssessmentOrdersPositiveResponseCandidate$inboundSchema:
  z.ZodType<
    GetAssessmentOrdersPositiveResponseCandidate,
    z.ZodTypeDef,
    unknown
  > = z.object({
    remote_id: z.nullable(z.string()),
    email: z.string(),
    first_name: z.nullable(z.string()),
    last_name: z.nullable(z.string()),
    phone: z.nullable(z.string()),
  });

export function getAssessmentOrdersPositiveResponseCandidateFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentOrdersPositiveResponseCandidate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponseCandidate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentOrdersPositiveResponseCandidate' from JSON`,
  );
}

/** @internal */
export const GetAssessmentOrdersPositiveResponseApplication$inboundSchema:
  z.ZodType<
    GetAssessmentOrdersPositiveResponseApplication,
    z.ZodTypeDef,
    unknown
  > = z.object({
    remote_id: z.nullable(z.string()),
  });

export function getAssessmentOrdersPositiveResponseApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentOrdersPositiveResponseApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponseApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentOrdersPositiveResponseApplication' from JSON`,
  );
}

/** @internal */
export const GetAssessmentOrdersPositiveResponseLocation$inboundSchema:
  z.ZodType<
    GetAssessmentOrdersPositiveResponseLocation,
    z.ZodTypeDef,
    unknown
  > = z.object({
    street_1: z.nullable(z.string()).optional(),
    street_2: z.nullable(z.string()).optional(),
    city: z.nullable(z.string()).optional(),
    state: z.nullable(z.string()).optional(),
    zip_code: z.nullable(z.string()).optional(),
    country: z.nullable(z.string()).optional(),
    raw: z.nullable(z.string()).optional(),
  });

export function getAssessmentOrdersPositiveResponseLocationFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentOrdersPositiveResponseLocation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponseLocation$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentOrdersPositiveResponseLocation' from JSON`,
  );
}

/** @internal */
export const GetAssessmentOrdersPositiveResponseHiringTeamRole$inboundSchema:
  z.ZodNativeEnum<typeof GetAssessmentOrdersPositiveResponseHiringTeamRole> = z
    .nativeEnum(GetAssessmentOrdersPositiveResponseHiringTeamRole);

/** @internal */
export const GetAssessmentOrdersPositiveResponseHiringTeam$inboundSchema:
  z.ZodType<
    GetAssessmentOrdersPositiveResponseHiringTeam,
    z.ZodTypeDef,
    unknown
  > = z.object({
    remote_id: z.nullable(z.string()),
    email: z.nullable(z.string()),
    first_name: z.nullable(z.string()),
    last_name: z.nullable(z.string()),
    hiring_team_roles: z.array(
      GetAssessmentOrdersPositiveResponseHiringTeamRole$inboundSchema,
    ),
  });

export function getAssessmentOrdersPositiveResponseHiringTeamFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentOrdersPositiveResponseHiringTeam,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponseHiringTeam$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentOrdersPositiveResponseHiringTeam' from JSON`,
  );
}

/** @internal */
export const GetAssessmentOrdersPositiveResponseJob$inboundSchema: z.ZodType<
  GetAssessmentOrdersPositiveResponseJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  remote_id: z.nullable(z.string()),
  name: z.nullable(z.string()),
  job_code: z.nullable(z.string()),
  description: z.nullable(z.string()),
  location: z.nullable(
    z.lazy(() => GetAssessmentOrdersPositiveResponseLocation$inboundSchema),
  ),
  hiring_team: z.array(
    z.lazy(() => GetAssessmentOrdersPositiveResponseHiringTeam$inboundSchema),
  ),
});

export function getAssessmentOrdersPositiveResponseJobFromJSON(
  jsonString: string,
): SafeParseResult<GetAssessmentOrdersPositiveResponseJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponseJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssessmentOrdersPositiveResponseJob' from JSON`,
  );
}

/** @internal */
export const GetAssessmentOrdersPositiveResponseResult$inboundSchema: z.ZodType<
  GetAssessmentOrdersPositiveResponseResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  package_id: z.string(),
  status: GetAssessmentOrdersPositiveResponseStatus$inboundSchema,
  candidate: z.lazy(() =>
    GetAssessmentOrdersPositiveResponseCandidate$inboundSchema
  ),
  application: z.lazy(() =>
    GetAssessmentOrdersPositiveResponseApplication$inboundSchema
  ),
  job: z.lazy(() => GetAssessmentOrdersPositiveResponseJob$inboundSchema),
});

export function getAssessmentOrdersPositiveResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentOrdersPositiveResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentOrdersPositiveResponseResult' from JSON`,
  );
}

/** @internal */
export const GetAssessmentOrdersPositiveResponseData$inboundSchema: z.ZodType<
  GetAssessmentOrdersPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  next: z.nullable(z.string()),
  results: z.array(
    z.lazy(() => GetAssessmentOrdersPositiveResponseResult$inboundSchema),
  ),
});

export function getAssessmentOrdersPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentOrdersPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentOrdersPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const GetAssessmentOrdersPositiveResponse$inboundSchema: z.ZodType<
  GetAssessmentOrdersPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetAssessmentOrdersPositiveResponseData$inboundSchema),
});

export function getAssessmentOrdersPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAssessmentOrdersPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentOrdersPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssessmentOrdersPositiveResponse' from JSON`,
  );
}
