/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const GetAssessmentPackagesPositiveResponseType = {
  Behavioral: "BEHAVIORAL",
  VideoInterview: "VIDEO_INTERVIEW",
  SkillsTest: "SKILLS_TEST",
  BackgroundCheck: "BACKGROUND_CHECK",
  ReferenceCheck: "REFERENCE_CHECK",
} as const;
export type GetAssessmentPackagesPositiveResponseType = ClosedEnum<
  typeof GetAssessmentPackagesPositiveResponseType
>;

export type GetAssessmentPackagesPositiveResponsePackage = {
  id: string;
  name: string;
  description: string;
  /**
   * YYYY-MM-DDTHH:mm:ss.sssZ
   */
  updated_at: Date | null;
  type: GetAssessmentPackagesPositiveResponseType | null;
};

export type GetAssessmentPackagesPositiveResponseData = {
  packages: Array<GetAssessmentPackagesPositiveResponsePackage>;
};

export type GetAssessmentPackagesPositiveResponse = {
  status: "success";
  data: GetAssessmentPackagesPositiveResponseData;
};

/** @internal */
export const GetAssessmentPackagesPositiveResponseType$inboundSchema:
  z.ZodNativeEnum<typeof GetAssessmentPackagesPositiveResponseType> = z
    .nativeEnum(GetAssessmentPackagesPositiveResponseType);

/** @internal */
export const GetAssessmentPackagesPositiveResponsePackage$inboundSchema:
  z.ZodType<
    GetAssessmentPackagesPositiveResponsePackage,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    updated_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    type: z.nullable(GetAssessmentPackagesPositiveResponseType$inboundSchema),
  });

export function getAssessmentPackagesPositiveResponsePackageFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentPackagesPositiveResponsePackage,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentPackagesPositiveResponsePackage$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentPackagesPositiveResponsePackage' from JSON`,
  );
}

/** @internal */
export const GetAssessmentPackagesPositiveResponseData$inboundSchema: z.ZodType<
  GetAssessmentPackagesPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  packages: z.array(
    z.lazy(() => GetAssessmentPackagesPositiveResponsePackage$inboundSchema),
  ),
});

export function getAssessmentPackagesPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAssessmentPackagesPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentPackagesPositiveResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAssessmentPackagesPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const GetAssessmentPackagesPositiveResponse$inboundSchema: z.ZodType<
  GetAssessmentPackagesPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetAssessmentPackagesPositiveResponseData$inboundSchema),
});

export function getAssessmentPackagesPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAssessmentPackagesPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAssessmentPackagesPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssessmentPackagesPositiveResponse' from JSON`,
  );
}
