/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetAtsRejectionReasonsPositiveResponseResult = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string;
  /**
   * The title of the rejection reason.
   */
  name: string | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
   */
  remote_deleted_at: Date | null;
};

export type GetAtsRejectionReasonsPositiveResponseData = {
  /**
   * Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages.
   */
  next: string | null;
  results: Array<GetAtsRejectionReasonsPositiveResponseResult>;
};

export type GetAtsRejectionReasonsPositiveResponse = {
  status: "success";
  data: GetAtsRejectionReasonsPositiveResponseData;
};

/** @internal */
export const GetAtsRejectionReasonsPositiveResponseResult$inboundSchema:
  z.ZodType<
    GetAtsRejectionReasonsPositiveResponseResult,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    remote_id: z.string(),
    name: z.nullable(z.string()),
    changed_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    remote_deleted_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
  });

export function getAtsRejectionReasonsPositiveResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAtsRejectionReasonsPositiveResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAtsRejectionReasonsPositiveResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAtsRejectionReasonsPositiveResponseResult' from JSON`,
  );
}

/** @internal */
export const GetAtsRejectionReasonsPositiveResponseData$inboundSchema:
  z.ZodType<GetAtsRejectionReasonsPositiveResponseData, z.ZodTypeDef, unknown> =
    z.object({
      next: z.nullable(z.string()),
      results: z.array(
        z.lazy(() =>
          GetAtsRejectionReasonsPositiveResponseResult$inboundSchema
        ),
      ),
    });

export function getAtsRejectionReasonsPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAtsRejectionReasonsPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAtsRejectionReasonsPositiveResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAtsRejectionReasonsPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const GetAtsRejectionReasonsPositiveResponse$inboundSchema: z.ZodType<
  GetAtsRejectionReasonsPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetAtsRejectionReasonsPositiveResponseData$inboundSchema),
});

export function getAtsRejectionReasonsPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAtsRejectionReasonsPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAtsRejectionReasonsPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAtsRejectionReasonsPositiveResponse' from JSON`,
  );
}
