/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetCheckApiKeyPositiveResponseData = {
  environment_id: string;
};

export type GetCheckApiKeyPositiveResponse = {
  status: "success";
  data: GetCheckApiKeyPositiveResponseData;
};

/** @internal */
export const GetCheckApiKeyPositiveResponseData$inboundSchema: z.ZodType<
  GetCheckApiKeyPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  environment_id: z.string(),
});

export function getCheckApiKeyPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCheckApiKeyPositiveResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetCheckApiKeyPositiveResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCheckApiKeyPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const GetCheckApiKeyPositiveResponse$inboundSchema: z.ZodType<
  GetCheckApiKeyPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetCheckApiKeyPositiveResponseData$inboundSchema),
});

export function getCheckApiKeyPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCheckApiKeyPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCheckApiKeyPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCheckApiKeyPositiveResponse' from JSON`,
  );
}
