/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const GetHrisEmploymentsPositiveResponsePayPeriod = {
  Hour: "HOUR",
  Day: "DAY",
  Week: "WEEK",
  TwoWeeks: "TWO_WEEKS",
  HalfMonth: "HALF_MONTH",
  Month: "MONTH",
  TwoMonths: "TWO_MONTHS",
  Quarter: "QUARTER",
  HalfYear: "HALF_YEAR",
  Year: "YEAR",
} as const;
export type GetHrisEmploymentsPositiveResponsePayPeriod = OpenEnum<
  typeof GetHrisEmploymentsPositiveResponsePayPeriod
>;

export const GetHrisEmploymentsPositiveResponsePayFrequency = {
  Daily: "DAILY",
  Weekly: "WEEKLY",
  Biweekly: "BIWEEKLY",
  Monthly: "MONTHLY",
  Semimonthly: "SEMIMONTHLY",
  Quarterly: "QUARTERLY",
  Semiannually: "SEMIANNUALLY",
  Annually: "ANNUALLY",
  ProRata: "PRO_RATA",
} as const;
export type GetHrisEmploymentsPositiveResponsePayFrequency = OpenEnum<
  typeof GetHrisEmploymentsPositiveResponsePayFrequency
>;

export const GetHrisEmploymentsPositiveResponseEmploymentType = {
  FullTime: "FULL_TIME",
  PartTime: "PART_TIME",
  Contract: "CONTRACT",
  Internship: "INTERNSHIP",
  Freelance: "FREELANCE",
  WorkingStudent: "WORKING_STUDENT",
  Apprenticeship: "APPRENTICESHIP",
  Training: "TRAINING",
} as const;
export type GetHrisEmploymentsPositiveResponseEmploymentType = OpenEnum<
  typeof GetHrisEmploymentsPositiveResponseEmploymentType
>;

export type GetHrisEmploymentsPositiveResponseResult = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string | null;
  /**
   * The Kombo ID of the employment’s employee. The ID can be used to retrieve the employee from the `get employees` endpoint.
   */
  employee_id: string;
  /**
   * This field can contain historic job titles. Please use the `job_title` field on the employee for the active job title of an employee.
   */
  job_title: string | null;
  /**
   * The monetary amount paid to an employee.
   */
  pay_rate: number | null;
  /**
   * The time interval which the `pay_rate` is describing.
   *
   * @remarks
   *
   * A `pay_rate` value of `12000` with a `pay_period` of `YEAR` would indicate that the employee receives 12000 over the course of a year. In rare cases where we can’t find a clear mapping, the original string is passed through.
   */
  pay_period?: GetHrisEmploymentsPositiveResponsePayPeriod | null | undefined;
  /**
   * The time interval at which the employee receives payment.
   *
   * @remarks
   *
   * A `pay_rate` of `12000`, with a `pay_period` of `YEAR`, and a `pay_frequency` of `MONTHLY` would indicate that the employee is paid 1000 every month. In rare cases where we can’t find a clear mapping, the original string is passed through.
   */
  pay_frequency?:
    | GetHrisEmploymentsPositiveResponsePayFrequency
    | null
    | undefined;
  /**
   * The employee’s current employment type:
   *
   * @remarks
   *
   * - `FULL_TIME`: the employee is actively employed
   * - `PART_TIME`: the employee is working only part of the usual working hours
   * - `CONTRACT`: the employee is working temporarily under a contract
   * - `INTERNSHIP`: the employee is working as an intern
   * - `FREELANCE`: the employee is working as a freelancer
   * - `WORKING_STUDENT`: the employee is working as a working student
   * - `APPRENTICESHIP`: the employee is working in an apprenticeship
   * - `TRAINING`: the employee is working in a training program
   *
   *  In rare cases where we can’t find a clear mapping, the original string is passed through.
   */
  employment_type?:
    | GetHrisEmploymentsPositiveResponseEmploymentType
    | null
    | undefined;
  /**
   * The currency that the employee is paid in. Usually returned in [ISO 4217 currency codes](https://www.iso.org/iso-4217-currency-codes.html).
   */
  pay_currency: string | null;
  /**
   * The date of when the employment started.
   */
  effective_date: Date | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
   */
  remote_deleted_at: Date | null;
  /**
   * A key-value store of fields not covered by the schema. [Read more](/custom-fields)
   */
  custom_fields: { [k: string]: any } | null;
};

export type GetHrisEmploymentsPositiveResponseData = {
  /**
   * Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages.
   */
  next: string | null;
  results: Array<GetHrisEmploymentsPositiveResponseResult>;
};

export type GetHrisEmploymentsPositiveResponse = {
  status: "success";
  data: GetHrisEmploymentsPositiveResponseData;
};

/** @internal */
export const GetHrisEmploymentsPositiveResponsePayPeriod$inboundSchema:
  z.ZodType<
    GetHrisEmploymentsPositiveResponsePayPeriod,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(GetHrisEmploymentsPositiveResponsePayPeriod);

/** @internal */
export const GetHrisEmploymentsPositiveResponsePayFrequency$inboundSchema:
  z.ZodType<
    GetHrisEmploymentsPositiveResponsePayFrequency,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(GetHrisEmploymentsPositiveResponsePayFrequency);

/** @internal */
export const GetHrisEmploymentsPositiveResponseEmploymentType$inboundSchema:
  z.ZodType<
    GetHrisEmploymentsPositiveResponseEmploymentType,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(GetHrisEmploymentsPositiveResponseEmploymentType);

/** @internal */
export const GetHrisEmploymentsPositiveResponseResult$inboundSchema: z.ZodType<
  GetHrisEmploymentsPositiveResponseResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  remote_id: z.nullable(z.string()),
  employee_id: z.string(),
  job_title: z.nullable(z.string()),
  pay_rate: z.nullable(z.number()),
  pay_period: z.nullable(
    GetHrisEmploymentsPositiveResponsePayPeriod$inboundSchema,
  ).optional(),
  pay_frequency: z.nullable(
    GetHrisEmploymentsPositiveResponsePayFrequency$inboundSchema,
  ).optional(),
  employment_type: z.nullable(
    GetHrisEmploymentsPositiveResponseEmploymentType$inboundSchema,
  ).optional(),
  pay_currency: z.nullable(z.string()),
  effective_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  changed_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  remote_deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  custom_fields: z.nullable(z.record(z.any())),
});

export function getHrisEmploymentsPositiveResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetHrisEmploymentsPositiveResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisEmploymentsPositiveResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetHrisEmploymentsPositiveResponseResult' from JSON`,
  );
}

/** @internal */
export const GetHrisEmploymentsPositiveResponseData$inboundSchema: z.ZodType<
  GetHrisEmploymentsPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  next: z.nullable(z.string()),
  results: z.array(
    z.lazy(() => GetHrisEmploymentsPositiveResponseResult$inboundSchema),
  ),
});

export function getHrisEmploymentsPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisEmploymentsPositiveResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisEmploymentsPositiveResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisEmploymentsPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const GetHrisEmploymentsPositiveResponse$inboundSchema: z.ZodType<
  GetHrisEmploymentsPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetHrisEmploymentsPositiveResponseData$inboundSchema),
});

export function getHrisEmploymentsPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisEmploymentsPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisEmploymentsPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisEmploymentsPositiveResponse' from JSON`,
  );
}
