/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The time-unit of the absence.
 */
export const GetHrisAbsenceTypesPositiveResponseUnit = {
  Hours: "HOURS",
  Days: "DAYS",
} as const;
/**
 * The time-unit of the absence.
 */
export type GetHrisAbsenceTypesPositiveResponseUnit = ClosedEnum<
  typeof GetHrisAbsenceTypesPositiveResponseUnit
>;

export type GetHrisAbsenceTypesPositiveResponseResult = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string;
  /**
   * The absence’s name.
   */
  name: string | null;
  /**
   * The time-unit of the absence.
   */
  unit: GetHrisAbsenceTypesPositiveResponseUnit | null;
  /**
   * Whether the integration supports half-day absences (represented through `start_half_day` and `end_half_day`) for this absence type.
   */
  half_days_supported: boolean | null;
  /**
   * `true` if the system supports exact times (absences with a `start_time` and an `end_time`) for this absence, `false` if not.
   */
  exact_times_supported: boolean | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
   */
  remote_deleted_at: Date | null;
};

export type GetHrisAbsenceTypesPositiveResponseData = {
  /**
   * Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages.
   */
  next: string | null;
  results: Array<GetHrisAbsenceTypesPositiveResponseResult>;
};

export type GetHrisAbsenceTypesPositiveResponse = {
  status: "success";
  data: GetHrisAbsenceTypesPositiveResponseData;
};

/** @internal */
export const GetHrisAbsenceTypesPositiveResponseUnit$inboundSchema:
  z.ZodNativeEnum<typeof GetHrisAbsenceTypesPositiveResponseUnit> = z
    .nativeEnum(GetHrisAbsenceTypesPositiveResponseUnit);

/** @internal */
export const GetHrisAbsenceTypesPositiveResponseUnit$outboundSchema:
  z.ZodNativeEnum<typeof GetHrisAbsenceTypesPositiveResponseUnit> =
    GetHrisAbsenceTypesPositiveResponseUnit$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHrisAbsenceTypesPositiveResponseUnit$ {
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseUnit$inboundSchema` instead. */
  export const inboundSchema =
    GetHrisAbsenceTypesPositiveResponseUnit$inboundSchema;
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseUnit$outboundSchema` instead. */
  export const outboundSchema =
    GetHrisAbsenceTypesPositiveResponseUnit$outboundSchema;
}

/** @internal */
export const GetHrisAbsenceTypesPositiveResponseResult$inboundSchema: z.ZodType<
  GetHrisAbsenceTypesPositiveResponseResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  remote_id: z.string(),
  name: z.nullable(z.string()),
  unit: z.nullable(GetHrisAbsenceTypesPositiveResponseUnit$inboundSchema),
  half_days_supported: z.nullable(z.boolean()),
  exact_times_supported: z.nullable(z.boolean()),
  changed_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  remote_deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
});

/** @internal */
export type GetHrisAbsenceTypesPositiveResponseResult$Outbound = {
  id: string;
  remote_id: string;
  name: string | null;
  unit: string | null;
  half_days_supported: boolean | null;
  exact_times_supported: boolean | null;
  changed_at: string;
  remote_deleted_at: string | null;
};

/** @internal */
export const GetHrisAbsenceTypesPositiveResponseResult$outboundSchema:
  z.ZodType<
    GetHrisAbsenceTypesPositiveResponseResult$Outbound,
    z.ZodTypeDef,
    GetHrisAbsenceTypesPositiveResponseResult
  > = z.object({
    id: z.string(),
    remote_id: z.string(),
    name: z.nullable(z.string()),
    unit: z.nullable(GetHrisAbsenceTypesPositiveResponseUnit$outboundSchema),
    half_days_supported: z.nullable(z.boolean()),
    exact_times_supported: z.nullable(z.boolean()),
    changed_at: z.date().transform(v => v.toISOString()),
    remote_deleted_at: z.nullable(z.date().transform(v => v.toISOString())),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHrisAbsenceTypesPositiveResponseResult$ {
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseResult$inboundSchema` instead. */
  export const inboundSchema =
    GetHrisAbsenceTypesPositiveResponseResult$inboundSchema;
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseResult$outboundSchema` instead. */
  export const outboundSchema =
    GetHrisAbsenceTypesPositiveResponseResult$outboundSchema;
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseResult$Outbound` instead. */
  export type Outbound = GetHrisAbsenceTypesPositiveResponseResult$Outbound;
}

export function getHrisAbsenceTypesPositiveResponseResultToJSON(
  getHrisAbsenceTypesPositiveResponseResult:
    GetHrisAbsenceTypesPositiveResponseResult,
): string {
  return JSON.stringify(
    GetHrisAbsenceTypesPositiveResponseResult$outboundSchema.parse(
      getHrisAbsenceTypesPositiveResponseResult,
    ),
  );
}

export function getHrisAbsenceTypesPositiveResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetHrisAbsenceTypesPositiveResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisAbsenceTypesPositiveResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetHrisAbsenceTypesPositiveResponseResult' from JSON`,
  );
}

/** @internal */
export const GetHrisAbsenceTypesPositiveResponseData$inboundSchema: z.ZodType<
  GetHrisAbsenceTypesPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  next: z.nullable(z.string()),
  results: z.array(
    z.lazy(() => GetHrisAbsenceTypesPositiveResponseResult$inboundSchema),
  ),
});

/** @internal */
export type GetHrisAbsenceTypesPositiveResponseData$Outbound = {
  next: string | null;
  results: Array<GetHrisAbsenceTypesPositiveResponseResult$Outbound>;
};

/** @internal */
export const GetHrisAbsenceTypesPositiveResponseData$outboundSchema: z.ZodType<
  GetHrisAbsenceTypesPositiveResponseData$Outbound,
  z.ZodTypeDef,
  GetHrisAbsenceTypesPositiveResponseData
> = z.object({
  next: z.nullable(z.string()),
  results: z.array(
    z.lazy(() => GetHrisAbsenceTypesPositiveResponseResult$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHrisAbsenceTypesPositiveResponseData$ {
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseData$inboundSchema` instead. */
  export const inboundSchema =
    GetHrisAbsenceTypesPositiveResponseData$inboundSchema;
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseData$outboundSchema` instead. */
  export const outboundSchema =
    GetHrisAbsenceTypesPositiveResponseData$outboundSchema;
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponseData$Outbound` instead. */
  export type Outbound = GetHrisAbsenceTypesPositiveResponseData$Outbound;
}

export function getHrisAbsenceTypesPositiveResponseDataToJSON(
  getHrisAbsenceTypesPositiveResponseData:
    GetHrisAbsenceTypesPositiveResponseData,
): string {
  return JSON.stringify(
    GetHrisAbsenceTypesPositiveResponseData$outboundSchema.parse(
      getHrisAbsenceTypesPositiveResponseData,
    ),
  );
}

export function getHrisAbsenceTypesPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetHrisAbsenceTypesPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisAbsenceTypesPositiveResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetHrisAbsenceTypesPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const GetHrisAbsenceTypesPositiveResponse$inboundSchema: z.ZodType<
  GetHrisAbsenceTypesPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetHrisAbsenceTypesPositiveResponseData$inboundSchema),
});

/** @internal */
export type GetHrisAbsenceTypesPositiveResponse$Outbound = {
  status: "success";
  data: GetHrisAbsenceTypesPositiveResponseData$Outbound;
};

/** @internal */
export const GetHrisAbsenceTypesPositiveResponse$outboundSchema: z.ZodType<
  GetHrisAbsenceTypesPositiveResponse$Outbound,
  z.ZodTypeDef,
  GetHrisAbsenceTypesPositiveResponse
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetHrisAbsenceTypesPositiveResponseData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHrisAbsenceTypesPositiveResponse$ {
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponse$inboundSchema` instead. */
  export const inboundSchema =
    GetHrisAbsenceTypesPositiveResponse$inboundSchema;
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetHrisAbsenceTypesPositiveResponse$outboundSchema;
  /** @deprecated use `GetHrisAbsenceTypesPositiveResponse$Outbound` instead. */
  export type Outbound = GetHrisAbsenceTypesPositiveResponse$Outbound;
}

export function getHrisAbsenceTypesPositiveResponseToJSON(
  getHrisAbsenceTypesPositiveResponse: GetHrisAbsenceTypesPositiveResponse,
): string {
  return JSON.stringify(
    GetHrisAbsenceTypesPositiveResponse$outboundSchema.parse(
      getHrisAbsenceTypesPositiveResponse,
    ),
  );
}

export function getHrisAbsenceTypesPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisAbsenceTypesPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisAbsenceTypesPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisAbsenceTypesPositiveResponse' from JSON`,
  );
}
