/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { catchUnrecognizedEnum, ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The unit of time for this absence. Can be `HOURS` or `DAYS`.
 */
export const GetHrisAbsencesPositiveResponseUnit = {
  Hours: "HOURS",
  Days: "DAYS",
} as const;
/**
 * The unit of time for this absence. Can be `HOURS` or `DAYS`.
 */
export type GetHrisAbsencesPositiveResponseUnit = ClosedEnum<
  typeof GetHrisAbsencesPositiveResponseUnit
>;

export const GetHrisAbsencesPositiveResponseStatus = {
  Requested: "REQUESTED",
  Approved: "APPROVED",
  Declined: "DECLINED",
  Cancelled: "CANCELLED",
  Deleted: "DELETED",
} as const;
export type GetHrisAbsencesPositiveResponseStatus = OpenEnum<
  typeof GetHrisAbsencesPositiveResponseStatus
>;

/**
 * The time-unit of the absence.
 */
export const GetHrisAbsencesPositiveResponseTypeUnit = {
  Hours: "HOURS",
  Days: "DAYS",
} as const;
/**
 * The time-unit of the absence.
 */
export type GetHrisAbsencesPositiveResponseTypeUnit = ClosedEnum<
  typeof GetHrisAbsencesPositiveResponseTypeUnit
>;

export type GetHrisAbsencesPositiveResponseType = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string;
  /**
   * The absence’s name.
   */
  name: string | null;
  /**
   * The time-unit of the absence.
   */
  unit: GetHrisAbsencesPositiveResponseTypeUnit | null;
  /**
   * Whether the integration supports half-day absences (represented through `start_half_day` and `end_half_day`) for this absence type.
   */
  half_days_supported: boolean | null;
  /**
   * `true` if the system supports exact times (absences with a `start_time` and an `end_time`) for this absence, `false` if not.
   */
  exact_times_supported: boolean | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
   */
  remote_deleted_at: Date | null;
};

export type GetHrisAbsencesPositiveResponseResult = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string | null;
  /**
   * The Kombo ID of the employee to which the absence belongs to. The ID can be used to retrieve the employee from the `get employees` endpoint.
   */
  employee_id: string;
  /**
   * The date this absence starts in the `yyyy-MM-dd` format.
   */
  start_date?: any | null | undefined;
  /**
   * The date this absence ends in the `yyyy-MM-dd` format.
   */
  end_date?: any | null | undefined;
  /**
   * `true` if the absence starts in the middle of the day, `false` if not, and `null` if the absence type doesn't support half-day absences. For multi-day absences, this only applies to the first day of the absence.
   */
  start_half_day: boolean | null;
  /**
   * `true` if the absence ends in the middle of the day, `false` if not, and `null` if the absence type doesn't support half-day absences. For multi-day absences, this only applies to the last day of the absence.
   */
  end_half_day: boolean | null;
  /**
   * The time at which this absence starts. Follows the format `HH:mm:ss` (e.g., `14:45:15`).
   */
  start_time?: any | null | undefined;
  /**
   * The time at which this absence ends. Follows the format `HH:mm:ss` (e.g., `14:45:15`).
   */
  end_time?: any | null | undefined;
  /**
   * The amount of time this absence takes.
   */
  amount: number | null;
  /**
   * The unit of time for this absence. Can be `HOURS` or `DAYS`.
   */
  unit: GetHrisAbsencesPositiveResponseUnit | null;
  /**
   * The absence’s current status. In rare cases where we can’t find a clear mapping, the original string is passed through.
   */
  status?: GetHrisAbsencesPositiveResponseStatus | null | undefined;
  /**
   * A note the employee has added to this absence.
   */
  employee_note: string | null;
  /**
   * The Kombo absence type ID of this absence.
   */
  type_id: string | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
   */
  remote_deleted_at: Date | null;
  type: GetHrisAbsencesPositiveResponseType | null;
};

export type GetHrisAbsencesPositiveResponseData = {
  /**
   * Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages.
   */
  next: string | null;
  results: Array<GetHrisAbsencesPositiveResponseResult>;
};

export type GetHrisAbsencesPositiveResponse = {
  status: "success";
  data: GetHrisAbsencesPositiveResponseData;
};

/** @internal */
export const GetHrisAbsencesPositiveResponseUnit$inboundSchema: z.ZodNativeEnum<
  typeof GetHrisAbsencesPositiveResponseUnit
> = z.nativeEnum(GetHrisAbsencesPositiveResponseUnit);

/** @internal */
export const GetHrisAbsencesPositiveResponseStatus$inboundSchema: z.ZodType<
  GetHrisAbsencesPositiveResponseStatus,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(GetHrisAbsencesPositiveResponseStatus),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const GetHrisAbsencesPositiveResponseTypeUnit$inboundSchema:
  z.ZodNativeEnum<typeof GetHrisAbsencesPositiveResponseTypeUnit> = z
    .nativeEnum(GetHrisAbsencesPositiveResponseTypeUnit);

/** @internal */
export const GetHrisAbsencesPositiveResponseType$inboundSchema: z.ZodType<
  GetHrisAbsencesPositiveResponseType,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  remote_id: z.string(),
  name: z.nullable(z.string()),
  unit: z.nullable(GetHrisAbsencesPositiveResponseTypeUnit$inboundSchema),
  half_days_supported: z.nullable(z.boolean()),
  exact_times_supported: z.nullable(z.boolean()),
  changed_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  remote_deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
});

export function getHrisAbsencesPositiveResponseTypeFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisAbsencesPositiveResponseType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisAbsencesPositiveResponseType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisAbsencesPositiveResponseType' from JSON`,
  );
}

/** @internal */
export const GetHrisAbsencesPositiveResponseResult$inboundSchema: z.ZodType<
  GetHrisAbsencesPositiveResponseResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  remote_id: z.nullable(z.string()),
  employee_id: z.string(),
  start_date: z.nullable(z.any()).optional(),
  end_date: z.nullable(z.any()).optional(),
  start_half_day: z.nullable(z.boolean()),
  end_half_day: z.nullable(z.boolean()),
  start_time: z.nullable(z.any()).optional(),
  end_time: z.nullable(z.any()).optional(),
  amount: z.nullable(z.number()),
  unit: z.nullable(GetHrisAbsencesPositiveResponseUnit$inboundSchema),
  status: z.nullable(GetHrisAbsencesPositiveResponseStatus$inboundSchema)
    .optional(),
  employee_note: z.nullable(z.string()),
  type_id: z.nullable(z.string()),
  changed_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  remote_deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  type: z.nullable(
    z.lazy(() => GetHrisAbsencesPositiveResponseType$inboundSchema),
  ),
});

export function getHrisAbsencesPositiveResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisAbsencesPositiveResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisAbsencesPositiveResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisAbsencesPositiveResponseResult' from JSON`,
  );
}

/** @internal */
export const GetHrisAbsencesPositiveResponseData$inboundSchema: z.ZodType<
  GetHrisAbsencesPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  next: z.nullable(z.string()),
  results: z.array(
    z.lazy(() => GetHrisAbsencesPositiveResponseResult$inboundSchema),
  ),
});

export function getHrisAbsencesPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisAbsencesPositiveResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetHrisAbsencesPositiveResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisAbsencesPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const GetHrisAbsencesPositiveResponse$inboundSchema: z.ZodType<
  GetHrisAbsencesPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => GetHrisAbsencesPositiveResponseData$inboundSchema),
});

export function getHrisAbsencesPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHrisAbsencesPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHrisAbsencesPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHrisAbsencesPositiveResponse' from JSON`,
  );
}
