/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const KomboAtsErrorStatus = {
  Error: "error",
} as const;
export type KomboAtsErrorStatus = ClosedEnum<typeof KomboAtsErrorStatus>;

/**
 * Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...).
 */
export const KomboAtsErrorCode = {
  PlatformRateLimitExceeded: "PLATFORM.RATE_LIMIT_EXCEEDED",
  PlatformIntegrationNotFound: "PLATFORM.INTEGRATION_NOT_FOUND",
  PlatformInputInvalid: "PLATFORM.INPUT_INVALID",
  PlatformUnknownError: "PLATFORM.UNKNOWN_ERROR",
  PlatformIpNotWhitelisted: "PLATFORM.IP_NOT_WHITELISTED",
  PlatformAuthenticationInvalid: "PLATFORM.AUTHENTICATION_INVALID",
  IntegrationPermissionMissing: "INTEGRATION.PERMISSION_MISSING",
  IntegrationAuthenticationInvalid: "INTEGRATION.AUTHENTICATION_INVALID",
  IntegrationQaFailed: "INTEGRATION.QA_FAILED",
  IntegrationSetupSyncPending: "INTEGRATION.SETUP_SYNC_PENDING",
  IntegrationSetupIncomplete: "INTEGRATION.SETUP_INCOMPLETE",
  IntegrationInactive: "INTEGRATION.INACTIVE",
  IntegrationModelNotAvailable: "INTEGRATION.MODEL_NOT_AVAILABLE",
  IntegrationModelDisabled: "INTEGRATION.MODEL_DISABLED",
  IntegrationActionNotAvailable: "INTEGRATION.ACTION_NOT_AVAILABLE",
  IntegrationActionDisabled: "INTEGRATION.ACTION_DISABLED",
  RemoteServiceUnavailable: "REMOTE.SERVICE_UNAVAILABLE",
  RemoteRateLimitExceeded: "REMOTE.RATE_LIMIT_EXCEEDED",
  RemoteInputInvalid: "REMOTE.INPUT_INVALID",
  RemoteUnknownHttpError: "REMOTE.UNKNOWN_HTTP_ERROR",
  AtsJobClosed: "ATS.JOB_CLOSED",
  AtsApplicationAlreadyExists: "ATS.APPLICATION_ALREADY_EXISTS",
} as const;
/**
 * Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...).
 */
export type KomboAtsErrorCode = ClosedEnum<typeof KomboAtsErrorCode>;

/**
 * Error details with structured code for programmatic handling.
 */
export type KomboAtsErrorError = {
  /**
   * Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...).
   */
  code: KomboAtsErrorCode | null;
  /**
   * A static, human-readable label.
   */
  title: string | null;
  /**
   * A dynamic, detailed description of what went wrong in this specific instance.
   */
  message: string;
  /**
   * The log page in the Kombo UI lists every interaction with full details. If you need assistance, share that link with our support team.
   */
  log_url: string | null;
};

/** @internal */
export const KomboAtsErrorStatus$inboundSchema: z.ZodNativeEnum<
  typeof KomboAtsErrorStatus
> = z.nativeEnum(KomboAtsErrorStatus);

/** @internal */
export const KomboAtsErrorCode$inboundSchema: z.ZodNativeEnum<
  typeof KomboAtsErrorCode
> = z.nativeEnum(KomboAtsErrorCode);

/** @internal */
export const KomboAtsErrorError$inboundSchema: z.ZodType<
  KomboAtsErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.nullable(KomboAtsErrorCode$inboundSchema),
  title: z.nullable(z.string()),
  message: z.string(),
  log_url: z.nullable(z.string()),
});

export function komboAtsErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<KomboAtsErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KomboAtsErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KomboAtsErrorError' from JSON`,
  );
}
