/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const KomboGeneralErrorStatus = {
  Error: "error",
} as const;
export type KomboGeneralErrorStatus = ClosedEnum<
  typeof KomboGeneralErrorStatus
>;

/**
 * Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...).
 */
export const KomboGeneralErrorCode = {
  PlatformRateLimitExceeded: "PLATFORM.RATE_LIMIT_EXCEEDED",
  PlatformIntegrationNotFound: "PLATFORM.INTEGRATION_NOT_FOUND",
  PlatformInputInvalid: "PLATFORM.INPUT_INVALID",
  PlatformUnknownError: "PLATFORM.UNKNOWN_ERROR",
  PlatformIpNotWhitelisted: "PLATFORM.IP_NOT_WHITELISTED",
  PlatformAuthenticationInvalid: "PLATFORM.AUTHENTICATION_INVALID",
} as const;
/**
 * Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...).
 */
export type KomboGeneralErrorCode = ClosedEnum<typeof KomboGeneralErrorCode>;

/**
 * Error details with structured code for programmatic handling.
 */
export type KomboGeneralErrorError = {
  /**
   * Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...).
   */
  code: KomboGeneralErrorCode | null;
  /**
   * A static, human-readable label.
   */
  title: string | null;
  /**
   * A dynamic, detailed description of what went wrong in this specific instance.
   */
  message: string;
  /**
   * The log page in the Kombo UI lists every interaction with full details. If you need assistance, share that link with our support team.
   */
  log_url: string | null;
};

/** @internal */
export const KomboGeneralErrorStatus$inboundSchema: z.ZodNativeEnum<
  typeof KomboGeneralErrorStatus
> = z.nativeEnum(KomboGeneralErrorStatus);

/** @internal */
export const KomboGeneralErrorCode$inboundSchema: z.ZodNativeEnum<
  typeof KomboGeneralErrorCode
> = z.nativeEnum(KomboGeneralErrorCode);

/** @internal */
export const KomboGeneralErrorError$inboundSchema: z.ZodType<
  KomboGeneralErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.nullable(KomboGeneralErrorCode$inboundSchema),
  title: z.nullable(z.string()),
  message: z.string(),
  log_url: z.nullable(z.string()),
});

export function komboGeneralErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<KomboGeneralErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KomboGeneralErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KomboGeneralErrorError' from JSON`,
  );
}
