/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Language of the connection flow UI.
 */
export const PostIntegrationsIntegrationIdRelinkRequestBodyLanguage = {
  En: "en",
  De: "de",
  Fr: "fr",
  It: "it",
  Es: "es",
} as const;
/**
 * Language of the connection flow UI.
 */
export type PostIntegrationsIntegrationIdRelinkRequestBodyLanguage = ClosedEnum<
  typeof PostIntegrationsIntegrationIdRelinkRequestBodyLanguage
>;

/**
 * The type of link you want to create. `EMBEDDED` is for the [embedded flow](../guides/connect/embedded-flow) using the Kombo Connect SDK (these links are valid for 1 hour) and `MAGIC_LINK` is for [magic links](../guides/connect/magic-links) which you send out manually to customers (there are valid for 1 year).
 *
 * @remarks
 *
 * This defaults to `EMBEDDED`, which is our recommended method of implementing the connection flow for a seamless user experience.
 */
export const PostIntegrationsIntegrationIdRelinkRequestBodyLinkType = {
  Embedded: "EMBEDDED",
  MagicLink: "MAGIC_LINK",
} as const;
/**
 * The type of link you want to create. `EMBEDDED` is for the [embedded flow](../guides/connect/embedded-flow) using the Kombo Connect SDK (these links are valid for 1 hour) and `MAGIC_LINK` is for [magic links](../guides/connect/magic-links) which you send out manually to customers (there are valid for 1 year).
 *
 * @remarks
 *
 * This defaults to `EMBEDDED`, which is our recommended method of implementing the connection flow for a seamless user experience.
 */
export type PostIntegrationsIntegrationIdRelinkRequestBodyLinkType = ClosedEnum<
  typeof PostIntegrationsIntegrationIdRelinkRequestBodyLinkType
>;

export type PostIntegrationsIntegrationIdRelinkRequestBody = {
  /**
   * Language of the connection flow UI.
   */
  language?:
    | PostIntegrationsIntegrationIdRelinkRequestBodyLanguage
    | null
    | undefined;
  /**
   * Specify a scope config which the integration will start using once the reconnection flow has been completed.
   *
   * @remarks
   *
   * This can be useful if you want to update the permissions of an integration, but only want the change to take effect once the user has updated their API credentials to prevent sync issues.
   */
  scope_config_id?: string | null | undefined;
  /**
   * The type of link you want to create. `EMBEDDED` is for the [embedded flow](../guides/connect/embedded-flow) using the Kombo Connect SDK (these links are valid for 1 hour) and `MAGIC_LINK` is for [magic links](../guides/connect/magic-links) which you send out manually to customers (there are valid for 1 year).
   *
   * @remarks
   *
   * This defaults to `EMBEDDED`, which is our recommended method of implementing the connection flow for a seamless user experience.
   */
  link_type?:
    | PostIntegrationsIntegrationIdRelinkRequestBodyLinkType
    | undefined;
};

/** @internal */
export const PostIntegrationsIntegrationIdRelinkRequestBodyLanguage$outboundSchema:
  z.ZodNativeEnum<
    typeof PostIntegrationsIntegrationIdRelinkRequestBodyLanguage
  > = z.nativeEnum(PostIntegrationsIntegrationIdRelinkRequestBodyLanguage);

/** @internal */
export const PostIntegrationsIntegrationIdRelinkRequestBodyLinkType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostIntegrationsIntegrationIdRelinkRequestBodyLinkType
  > = z.nativeEnum(PostIntegrationsIntegrationIdRelinkRequestBodyLinkType);

/** @internal */
export type PostIntegrationsIntegrationIdRelinkRequestBody$Outbound = {
  language: string | null;
  scope_config_id?: string | null | undefined;
  link_type: string;
};

/** @internal */
export const PostIntegrationsIntegrationIdRelinkRequestBody$outboundSchema:
  z.ZodType<
    PostIntegrationsIntegrationIdRelinkRequestBody$Outbound,
    z.ZodTypeDef,
    PostIntegrationsIntegrationIdRelinkRequestBody
  > = z.object({
    language: z.nullable(
      PostIntegrationsIntegrationIdRelinkRequestBodyLanguage$outboundSchema
        .default("en"),
    ),
    scope_config_id: z.nullable(z.string()).optional(),
    link_type:
      PostIntegrationsIntegrationIdRelinkRequestBodyLinkType$outboundSchema
        .default("EMBEDDED"),
  });

export function postIntegrationsIntegrationIdRelinkRequestBodyToJSON(
  postIntegrationsIntegrationIdRelinkRequestBody:
    PostIntegrationsIntegrationIdRelinkRequestBody,
): string {
  return JSON.stringify(
    PostIntegrationsIntegrationIdRelinkRequestBody$outboundSchema.parse(
      postIntegrationsIntegrationIdRelinkRequestBody,
    ),
  );
}
