/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PostAtsCandidatesPositiveResponsePhoneNumber = {
  phone_number: string;
  /**
   * Kombo exposes type information through this field. If we don't get any information from the tool, we will set this to `null`.
   */
  type?: string | null | undefined;
};

export type PostAtsCandidatesPositiveResponseEmailAddress = {
  email_address?: string | null | undefined;
  /**
   * Kombo exposes type information through this field. If we don't get any information from the tool, we will set this to `null`.
   */
  type: string | null;
};

export type PostAtsCandidatesPositiveResponseSocialMedia = {
  link?: string | null | undefined;
  type?: string | null | undefined;
  username?: string | null | undefined;
};

/**
 * Location of the candidate.
 */
export type PostAtsCandidatesPositiveResponseLocation = {
  city?: string | null | undefined;
  /**
   * Contains the ISO2 country code if possible. If not, it contains the original value.
   */
  country?: string | null | undefined;
  /**
   * If we have address data, this is filled with the raw address string.
   */
  raw?: string | null | undefined;
  state?: string | null | undefined;
  /**
   * If we can parse the address data, this field contains the first part of the street information.
   */
  street_1?: string | null | undefined;
  street_2?: string | null | undefined;
  zip_code?: string | null | undefined;
};

/**
 * Parsed status of the application. If Kombo identifies that the application was accepted and the candidate hired, it will be `HIRED`. If the application was rejected or the candidate declined, it will be `DECLINED`. If the application is still in process, it will be `PENDING`.
 *
 * @remarks
 * Kombo will always try to deliver this information as reliably as possible.
 */
export const PostAtsCandidatesPositiveResponseOutcome = {
  Pending: "PENDING",
  Hired: "HIRED",
  Declined: "DECLINED",
} as const;
/**
 * Parsed status of the application. If Kombo identifies that the application was accepted and the candidate hired, it will be `HIRED`. If the application was rejected or the candidate declined, it will be `DECLINED`. If the application is still in process, it will be `PENDING`.
 *
 * @remarks
 * Kombo will always try to deliver this information as reliably as possible.
 */
export type PostAtsCandidatesPositiveResponseOutcome = ClosedEnum<
  typeof PostAtsCandidatesPositiveResponseOutcome
>;

export type PostAtsCandidatesPositiveResponseCurrentStage = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The application stage name. For example, "Initial Screening".
   */
  name: string | null;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string | null;
  index: number | null;
};

export type PostAtsCandidatesPositiveResponseJob = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * Title of the job.
   */
  name: string | null;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string;
};

export type PostAtsCandidatesPositiveResponseApplication = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string | null;
  /**
   * Parsed status of the application. If Kombo identifies that the application was accepted and the candidate hired, it will be `HIRED`. If the application was rejected or the candidate declined, it will be `DECLINED`. If the application is still in process, it will be `PENDING`.
   *
   * @remarks
   * Kombo will always try to deliver this information as reliably as possible.
   */
  outcome: PostAtsCandidatesPositiveResponseOutcome | null;
  /**
   * Reason for the rejection of the candidate.
   */
  rejection_reason_name: string | null;
  /**
   * The time that the application was rejected.
   */
  rejected_at: Date | null;
  /**
   * URL to the application in the source ATS system. When embedding this in your system, please consider that not for all ATS a dedicated application URL is available, so you might need to fall back to the candidate URL.
   */
  remote_url: string | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was created in the remote system.
   */
  remote_created_at: Date | null;
  /**
   * A timestamp retrieved from the remote system, describing when the resource was last updated.
   */
  remote_updated_at: Date | null;
  current_stage: PostAtsCandidatesPositiveResponseCurrentStage | null;
  job: PostAtsCandidatesPositiveResponseJob | null;
};

export type PostAtsCandidatesPositiveResponseTag = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  name: string | null;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string | null;
};

export type PostAtsCandidatesPositiveResponseData = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string;
  /**
   * First name of the candidate.
   */
  first_name: string | null;
  /**
   * Last name of the candidate.
   */
  last_name: string | null;
  /**
   * The current company of the candidate.
   */
  company: string | null;
  /**
   * The current job title of the candidate.
   */
  title: string | null;
  /**
   * Whether the candidate’s profile is confidential in the ATS.
   */
  confidential: boolean | null;
  /**
   * The hiring source of the candidate. If you're a job board or recruiting service, you can use this to validate which candidates applied through your service and ensure that the correct referral compensation is paid out.
   */
  source: string | null;
  /**
   * A list of phone numbers of the candidate.
   */
  phone_numbers?:
    | Array<PostAtsCandidatesPositiveResponsePhoneNumber>
    | null
    | undefined;
  /**
   * A list of email addresses of the candidate with an optional type. If an email address is invalid, it will be filtered out.
   */
  email_addresses?:
    | Array<PostAtsCandidatesPositiveResponseEmailAddress>
    | null
    | undefined;
  /**
   * List of social media accounts of the candidate.
   */
  social_media?:
    | Array<PostAtsCandidatesPositiveResponseSocialMedia>
    | null
    | undefined;
  /**
   * Location of the candidate.
   */
  location?: PostAtsCandidatesPositiveResponseLocation | null | undefined;
  /**
   * A key-value store of fields not covered by the schema. [Read more](/custom-fields)
   */
  custom_fields: { [k: string]: any } | null;
  /**
   * URL to the candidate profile in the source ATS system. When embedding this in your system, please consider that not for all ATS a dedicated candidate profile URL is available, so you might need to fall back to the application URL.
   */
  remote_url: string | null;
  /**
   * The date and time the object was created in the remote system.
   */
  remote_created_at: Date | null;
  /**
   * A timestamp retrieved from the remote system, describing when the resource was last updated.
   */
  remote_updated_at: Date | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
   */
  remote_deleted_at: Date | null;
  applications: Array<PostAtsCandidatesPositiveResponseApplication>;
  tags: Array<PostAtsCandidatesPositiveResponseTag>;
};

export type PostAtsCandidatesPositiveResponseWarning = {
  message: string;
};

export type PostAtsCandidatesPositiveResponse = {
  status: "success";
  data: PostAtsCandidatesPositiveResponseData;
  /**
   * These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
   */
  warnings: Array<PostAtsCandidatesPositiveResponseWarning>;
};

/** @internal */
export const PostAtsCandidatesPositiveResponsePhoneNumber$inboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponsePhoneNumber,
    z.ZodTypeDef,
    unknown
  > = z.object({
    phone_number: z.string(),
    type: z.nullable(z.string()).optional(),
  });

/** @internal */
export type PostAtsCandidatesPositiveResponsePhoneNumber$Outbound = {
  phone_number: string;
  type?: string | null | undefined;
};

/** @internal */
export const PostAtsCandidatesPositiveResponsePhoneNumber$outboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponsePhoneNumber$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesPositiveResponsePhoneNumber
  > = z.object({
    phone_number: z.string(),
    type: z.nullable(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponsePhoneNumber$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponsePhoneNumber$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponsePhoneNumber$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponsePhoneNumber$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponsePhoneNumber$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponsePhoneNumber$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponsePhoneNumber$Outbound;
}

export function postAtsCandidatesPositiveResponsePhoneNumberToJSON(
  postAtsCandidatesPositiveResponsePhoneNumber:
    PostAtsCandidatesPositiveResponsePhoneNumber,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponsePhoneNumber$outboundSchema.parse(
      postAtsCandidatesPositiveResponsePhoneNumber,
    ),
  );
}

export function postAtsCandidatesPositiveResponsePhoneNumberFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesPositiveResponsePhoneNumber,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponsePhoneNumber$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesPositiveResponsePhoneNumber' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseEmailAddress$inboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseEmailAddress,
    z.ZodTypeDef,
    unknown
  > = z.object({
    email_address: z.nullable(z.string()).optional(),
    type: z.nullable(z.string()),
  });

/** @internal */
export type PostAtsCandidatesPositiveResponseEmailAddress$Outbound = {
  email_address?: string | null | undefined;
  type: string | null;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseEmailAddress$outboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseEmailAddress$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesPositiveResponseEmailAddress
  > = z.object({
    email_address: z.nullable(z.string()).optional(),
    type: z.nullable(z.string()),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseEmailAddress$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseEmailAddress$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseEmailAddress$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseEmailAddress$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseEmailAddress$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseEmailAddress$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseEmailAddress$Outbound;
}

export function postAtsCandidatesPositiveResponseEmailAddressToJSON(
  postAtsCandidatesPositiveResponseEmailAddress:
    PostAtsCandidatesPositiveResponseEmailAddress,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseEmailAddress$outboundSchema.parse(
      postAtsCandidatesPositiveResponseEmailAddress,
    ),
  );
}

export function postAtsCandidatesPositiveResponseEmailAddressFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesPositiveResponseEmailAddress,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseEmailAddress$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesPositiveResponseEmailAddress' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseSocialMedia$inboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseSocialMedia,
    z.ZodTypeDef,
    unknown
  > = z.object({
    link: z.nullable(z.string()).optional(),
    type: z.nullable(z.string()).optional(),
    username: z.nullable(z.string()).optional(),
  });

/** @internal */
export type PostAtsCandidatesPositiveResponseSocialMedia$Outbound = {
  link?: string | null | undefined;
  type?: string | null | undefined;
  username?: string | null | undefined;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseSocialMedia$outboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseSocialMedia$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesPositiveResponseSocialMedia
  > = z.object({
    link: z.nullable(z.string()).optional(),
    type: z.nullable(z.string()).optional(),
    username: z.nullable(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseSocialMedia$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseSocialMedia$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseSocialMedia$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseSocialMedia$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseSocialMedia$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseSocialMedia$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseSocialMedia$Outbound;
}

export function postAtsCandidatesPositiveResponseSocialMediaToJSON(
  postAtsCandidatesPositiveResponseSocialMedia:
    PostAtsCandidatesPositiveResponseSocialMedia,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseSocialMedia$outboundSchema.parse(
      postAtsCandidatesPositiveResponseSocialMedia,
    ),
  );
}

export function postAtsCandidatesPositiveResponseSocialMediaFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesPositiveResponseSocialMedia,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseSocialMedia$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesPositiveResponseSocialMedia' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseLocation$inboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseLocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  city: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()).optional(),
  raw: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  street_1: z.nullable(z.string()).optional(),
  street_2: z.nullable(z.string()).optional(),
  zip_code: z.nullable(z.string()).optional(),
});

/** @internal */
export type PostAtsCandidatesPositiveResponseLocation$Outbound = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  raw?: string | null | undefined;
  state?: string | null | undefined;
  street_1?: string | null | undefined;
  street_2?: string | null | undefined;
  zip_code?: string | null | undefined;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseLocation$outboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseLocation$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesPositiveResponseLocation
  > = z.object({
    city: z.nullable(z.string()).optional(),
    country: z.nullable(z.string()).optional(),
    raw: z.nullable(z.string()).optional(),
    state: z.nullable(z.string()).optional(),
    street_1: z.nullable(z.string()).optional(),
    street_2: z.nullable(z.string()).optional(),
    zip_code: z.nullable(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseLocation$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseLocation$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseLocation$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseLocation$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseLocation$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseLocation$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseLocation$Outbound;
}

export function postAtsCandidatesPositiveResponseLocationToJSON(
  postAtsCandidatesPositiveResponseLocation:
    PostAtsCandidatesPositiveResponseLocation,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseLocation$outboundSchema.parse(
      postAtsCandidatesPositiveResponseLocation,
    ),
  );
}

export function postAtsCandidatesPositiveResponseLocationFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesPositiveResponseLocation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseLocation$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesPositiveResponseLocation' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseOutcome$inboundSchema:
  z.ZodNativeEnum<typeof PostAtsCandidatesPositiveResponseOutcome> = z
    .nativeEnum(PostAtsCandidatesPositiveResponseOutcome);

/** @internal */
export const PostAtsCandidatesPositiveResponseOutcome$outboundSchema:
  z.ZodNativeEnum<typeof PostAtsCandidatesPositiveResponseOutcome> =
    PostAtsCandidatesPositiveResponseOutcome$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseOutcome$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseOutcome$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseOutcome$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseOutcome$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseOutcome$outboundSchema;
}

/** @internal */
export const PostAtsCandidatesPositiveResponseCurrentStage$inboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseCurrentStage,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    name: z.nullable(z.string()),
    remote_id: z.nullable(z.string()),
    index: z.nullable(z.number().int()),
  });

/** @internal */
export type PostAtsCandidatesPositiveResponseCurrentStage$Outbound = {
  id: string;
  name: string | null;
  remote_id: string | null;
  index: number | null;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseCurrentStage$outboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseCurrentStage$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesPositiveResponseCurrentStage
  > = z.object({
    id: z.string(),
    name: z.nullable(z.string()),
    remote_id: z.nullable(z.string()),
    index: z.nullable(z.number().int()),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseCurrentStage$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseCurrentStage$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseCurrentStage$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseCurrentStage$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseCurrentStage$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseCurrentStage$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseCurrentStage$Outbound;
}

export function postAtsCandidatesPositiveResponseCurrentStageToJSON(
  postAtsCandidatesPositiveResponseCurrentStage:
    PostAtsCandidatesPositiveResponseCurrentStage,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseCurrentStage$outboundSchema.parse(
      postAtsCandidatesPositiveResponseCurrentStage,
    ),
  );
}

export function postAtsCandidatesPositiveResponseCurrentStageFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesPositiveResponseCurrentStage,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseCurrentStage$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesPositiveResponseCurrentStage' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseJob$inboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  remote_id: z.string(),
});

/** @internal */
export type PostAtsCandidatesPositiveResponseJob$Outbound = {
  id: string;
  name: string | null;
  remote_id: string;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseJob$outboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseJob$Outbound,
  z.ZodTypeDef,
  PostAtsCandidatesPositiveResponseJob
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  remote_id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseJob$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseJob$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseJob$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseJob$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseJob$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseJob$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseJob$Outbound;
}

export function postAtsCandidatesPositiveResponseJobToJSON(
  postAtsCandidatesPositiveResponseJob: PostAtsCandidatesPositiveResponseJob,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseJob$outboundSchema.parse(
      postAtsCandidatesPositiveResponseJob,
    ),
  );
}

export function postAtsCandidatesPositiveResponseJobFromJSON(
  jsonString: string,
): SafeParseResult<PostAtsCandidatesPositiveResponseJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesPositiveResponseJob' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseApplication$inboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseApplication,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    remote_id: z.nullable(z.string()),
    outcome: z.nullable(PostAtsCandidatesPositiveResponseOutcome$inboundSchema),
    rejection_reason_name: z.nullable(z.string()),
    rejected_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    remote_url: z.nullable(z.string()),
    changed_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    remote_created_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    remote_updated_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    current_stage: z.nullable(
      z.lazy(() => PostAtsCandidatesPositiveResponseCurrentStage$inboundSchema),
    ),
    job: z.nullable(
      z.lazy(() => PostAtsCandidatesPositiveResponseJob$inboundSchema),
    ),
  });

/** @internal */
export type PostAtsCandidatesPositiveResponseApplication$Outbound = {
  id: string;
  remote_id: string | null;
  outcome: string | null;
  rejection_reason_name: string | null;
  rejected_at: string | null;
  remote_url: string | null;
  changed_at: string;
  remote_created_at: string | null;
  remote_updated_at: string | null;
  current_stage: PostAtsCandidatesPositiveResponseCurrentStage$Outbound | null;
  job: PostAtsCandidatesPositiveResponseJob$Outbound | null;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseApplication$outboundSchema:
  z.ZodType<
    PostAtsCandidatesPositiveResponseApplication$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesPositiveResponseApplication
  > = z.object({
    id: z.string(),
    remote_id: z.nullable(z.string()),
    outcome: z.nullable(
      PostAtsCandidatesPositiveResponseOutcome$outboundSchema,
    ),
    rejection_reason_name: z.nullable(z.string()),
    rejected_at: z.nullable(z.date().transform(v => v.toISOString())),
    remote_url: z.nullable(z.string()),
    changed_at: z.date().transform(v => v.toISOString()),
    remote_created_at: z.nullable(z.date().transform(v => v.toISOString())),
    remote_updated_at: z.nullable(z.date().transform(v => v.toISOString())),
    current_stage: z.nullable(
      z.lazy(() =>
        PostAtsCandidatesPositiveResponseCurrentStage$outboundSchema
      ),
    ),
    job: z.nullable(
      z.lazy(() => PostAtsCandidatesPositiveResponseJob$outboundSchema),
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseApplication$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseApplication$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseApplication$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseApplication$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseApplication$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseApplication$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseApplication$Outbound;
}

export function postAtsCandidatesPositiveResponseApplicationToJSON(
  postAtsCandidatesPositiveResponseApplication:
    PostAtsCandidatesPositiveResponseApplication,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseApplication$outboundSchema.parse(
      postAtsCandidatesPositiveResponseApplication,
    ),
  );
}

export function postAtsCandidatesPositiveResponseApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesPositiveResponseApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesPositiveResponseApplication' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseTag$inboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseTag,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  remote_id: z.nullable(z.string()),
});

/** @internal */
export type PostAtsCandidatesPositiveResponseTag$Outbound = {
  id: string;
  name: string | null;
  remote_id: string | null;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseTag$outboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseTag$Outbound,
  z.ZodTypeDef,
  PostAtsCandidatesPositiveResponseTag
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  remote_id: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseTag$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseTag$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseTag$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseTag$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseTag$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseTag$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseTag$Outbound;
}

export function postAtsCandidatesPositiveResponseTagToJSON(
  postAtsCandidatesPositiveResponseTag: PostAtsCandidatesPositiveResponseTag,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseTag$outboundSchema.parse(
      postAtsCandidatesPositiveResponseTag,
    ),
  );
}

export function postAtsCandidatesPositiveResponseTagFromJSON(
  jsonString: string,
): SafeParseResult<PostAtsCandidatesPositiveResponseTag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseTag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesPositiveResponseTag' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseData$inboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  remote_id: z.string(),
  first_name: z.nullable(z.string()),
  last_name: z.nullable(z.string()),
  company: z.nullable(z.string()),
  title: z.nullable(z.string()),
  confidential: z.nullable(z.boolean()),
  source: z.nullable(z.string()),
  phone_numbers: z.nullable(
    z.array(z.lazy(() =>
      PostAtsCandidatesPositiveResponsePhoneNumber$inboundSchema
    )),
  ).optional(),
  email_addresses: z.nullable(
    z.array(z.lazy(() =>
      PostAtsCandidatesPositiveResponseEmailAddress$inboundSchema
    )),
  ).optional(),
  social_media: z.nullable(
    z.array(z.lazy(() =>
      PostAtsCandidatesPositiveResponseSocialMedia$inboundSchema
    )),
  ).optional(),
  location: z.nullable(
    z.lazy(() => PostAtsCandidatesPositiveResponseLocation$inboundSchema),
  ).optional(),
  custom_fields: z.nullable(z.record(z.any())),
  remote_url: z.nullable(z.string()),
  remote_created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  remote_updated_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  changed_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  remote_deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  applications: z.array(
    z.lazy(() => PostAtsCandidatesPositiveResponseApplication$inboundSchema),
  ),
  tags: z.array(
    z.lazy(() => PostAtsCandidatesPositiveResponseTag$inboundSchema),
  ),
});

/** @internal */
export type PostAtsCandidatesPositiveResponseData$Outbound = {
  id: string;
  remote_id: string;
  first_name: string | null;
  last_name: string | null;
  company: string | null;
  title: string | null;
  confidential: boolean | null;
  source: string | null;
  phone_numbers?:
    | Array<PostAtsCandidatesPositiveResponsePhoneNumber$Outbound>
    | null
    | undefined;
  email_addresses?:
    | Array<PostAtsCandidatesPositiveResponseEmailAddress$Outbound>
    | null
    | undefined;
  social_media?:
    | Array<PostAtsCandidatesPositiveResponseSocialMedia$Outbound>
    | null
    | undefined;
  location?:
    | PostAtsCandidatesPositiveResponseLocation$Outbound
    | null
    | undefined;
  custom_fields: { [k: string]: any } | null;
  remote_url: string | null;
  remote_created_at: string | null;
  remote_updated_at: string | null;
  changed_at: string;
  remote_deleted_at: string | null;
  applications: Array<PostAtsCandidatesPositiveResponseApplication$Outbound>;
  tags: Array<PostAtsCandidatesPositiveResponseTag$Outbound>;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseData$outboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseData$Outbound,
  z.ZodTypeDef,
  PostAtsCandidatesPositiveResponseData
> = z.object({
  id: z.string(),
  remote_id: z.string(),
  first_name: z.nullable(z.string()),
  last_name: z.nullable(z.string()),
  company: z.nullable(z.string()),
  title: z.nullable(z.string()),
  confidential: z.nullable(z.boolean()),
  source: z.nullable(z.string()),
  phone_numbers: z.nullable(
    z.array(z.lazy(() =>
      PostAtsCandidatesPositiveResponsePhoneNumber$outboundSchema
    )),
  ).optional(),
  email_addresses: z.nullable(
    z.array(z.lazy(() =>
      PostAtsCandidatesPositiveResponseEmailAddress$outboundSchema
    )),
  ).optional(),
  social_media: z.nullable(
    z.array(z.lazy(() =>
      PostAtsCandidatesPositiveResponseSocialMedia$outboundSchema
    )),
  ).optional(),
  location: z.nullable(
    z.lazy(() => PostAtsCandidatesPositiveResponseLocation$outboundSchema),
  ).optional(),
  custom_fields: z.nullable(z.record(z.any())),
  remote_url: z.nullable(z.string()),
  remote_created_at: z.nullable(z.date().transform(v => v.toISOString())),
  remote_updated_at: z.nullable(z.date().transform(v => v.toISOString())),
  changed_at: z.date().transform(v => v.toISOString()),
  remote_deleted_at: z.nullable(z.date().transform(v => v.toISOString())),
  applications: z.array(
    z.lazy(() => PostAtsCandidatesPositiveResponseApplication$outboundSchema),
  ),
  tags: z.array(
    z.lazy(() => PostAtsCandidatesPositiveResponseTag$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseData$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseData$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseData$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseData$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseData$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseData$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseData$Outbound;
}

export function postAtsCandidatesPositiveResponseDataToJSON(
  postAtsCandidatesPositiveResponseData: PostAtsCandidatesPositiveResponseData,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseData$outboundSchema.parse(
      postAtsCandidatesPositiveResponseData,
    ),
  );
}

export function postAtsCandidatesPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PostAtsCandidatesPositiveResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponseWarning$inboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseWarning,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type PostAtsCandidatesPositiveResponseWarning$Outbound = {
  message: string;
};

/** @internal */
export const PostAtsCandidatesPositiveResponseWarning$outboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponseWarning$Outbound,
  z.ZodTypeDef,
  PostAtsCandidatesPositiveResponseWarning
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponseWarning$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponseWarning$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesPositiveResponseWarning$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseWarning$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponseWarning$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponseWarning$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponseWarning$Outbound;
}

export function postAtsCandidatesPositiveResponseWarningToJSON(
  postAtsCandidatesPositiveResponseWarning:
    PostAtsCandidatesPositiveResponseWarning,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponseWarning$outboundSchema.parse(
      postAtsCandidatesPositiveResponseWarning,
    ),
  );
}

export function postAtsCandidatesPositiveResponseWarningFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesPositiveResponseWarning,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesPositiveResponseWarning$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesPositiveResponseWarning' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesPositiveResponse$inboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => PostAtsCandidatesPositiveResponseData$inboundSchema),
  warnings: z.array(
    z.lazy(() => PostAtsCandidatesPositiveResponseWarning$inboundSchema),
  ),
});

/** @internal */
export type PostAtsCandidatesPositiveResponse$Outbound = {
  status: "success";
  data: PostAtsCandidatesPositiveResponseData$Outbound;
  warnings: Array<PostAtsCandidatesPositiveResponseWarning$Outbound>;
};

/** @internal */
export const PostAtsCandidatesPositiveResponse$outboundSchema: z.ZodType<
  PostAtsCandidatesPositiveResponse$Outbound,
  z.ZodTypeDef,
  PostAtsCandidatesPositiveResponse
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => PostAtsCandidatesPositiveResponseData$outboundSchema),
  warnings: z.array(
    z.lazy(() => PostAtsCandidatesPositiveResponseWarning$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesPositiveResponse$ {
  /** @deprecated use `PostAtsCandidatesPositiveResponse$inboundSchema` instead. */
  export const inboundSchema = PostAtsCandidatesPositiveResponse$inboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesPositiveResponse$outboundSchema;
  /** @deprecated use `PostAtsCandidatesPositiveResponse$Outbound` instead. */
  export type Outbound = PostAtsCandidatesPositiveResponse$Outbound;
}

export function postAtsCandidatesPositiveResponseToJSON(
  postAtsCandidatesPositiveResponse: PostAtsCandidatesPositiveResponse,
): string {
  return JSON.stringify(
    PostAtsCandidatesPositiveResponse$outboundSchema.parse(
      postAtsCandidatesPositiveResponse,
    ),
  );
}

export function postAtsCandidatesPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostAtsCandidatesPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostAtsCandidatesPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesPositiveResponse' from JSON`,
  );
}
