/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
 */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyType = {
  Cv: "CV",
  CoverLetter: "COVER_LETTER",
  Other: "OTHER",
} as const;
/**
 * Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
 */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyType = ClosedEnum<
  typeof PostAtsCandidatesCandidateIdAttachmentsRequestBodyType
>;

export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment = {
  /**
   * File name of the file you want to upload. We recommend providing something human-readable with a valid file extension (like `Resume.pdf`), as this might be shown in your customer's system.
   */
  name: string;
  /**
   * Content/MIME type of the file (e.g., `application/pdf`).
   *
   * @remarks
   *
   * If you provide `data`, this is required. If you provide `data_url`, this is optional and we'll attempt to use the `Content-Type` header of the response.
   *
   * **Note:** Please validate that the content type you provide is actually meaningful (and not something generic like [`application/octet-stream`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types#applicationoctet-stream)). Especially when using object storage (like AWS S3), it's easy to accidentally discard the content types of user-provided files, so make sure to explicitly persist them when processing uploads from your users (see guides for [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#SysMetadata), [Google Cloud](https://cloud.google.com/storage/docs/metadata#content-type), and [Azure](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-all-blob-types)).
   */
  content_type?: string | undefined;
  /**
   * URL to the file you want to upload that can be accessed without authentication headers. We will download the content immediately when receiving the request, so the URL can be short-lived.
   *
   * @remarks
   *
   * If you're using an object storage provider (like AWS S3), we strongly recommend providing a signed URL for secure access (see guides for [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html), [Google Cloud](https://cloud.google.com/storage/docs/access-control/signed-urls), and [Azure](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview)).
   *
   * **Note:** You must provide either this or `data_url`. We recommend `data_url` over `data` for most cases.
   */
  data_url?: string | undefined;
  /**
   * Base64-encoded contents of the file you want to upload.
   *
   * @remarks
   *
   * **Note:** You must provide either this or `data_url`. We recommend `data_url` over `data` for most cases.
   */
  data?: string | undefined;
  /**
   * Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
   */
  type: PostAtsCandidatesCandidateIdAttachmentsRequestBodyType;
};

/**
 * Headers we will pass with `POST` requests to Greenhouse.
 */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders = {
  /**
   * ID of the the user that will show up as having performed the action in Greenhouse. We already pass a value by default, but you can use this to override it.
   */
  on_behalf_of?: string | null | undefined;
};

/**
 * Fields specific to Greenhouse.
 */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse = {
  /**
   * Headers we will pass with `POST` requests to Greenhouse.
   */
  post_headers?:
    | PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders
    | undefined;
};

/**
 * Workable specific remote fields for ATS actions.
 */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable = {
  /**
   * The remote ID of the user that will be displayed in the UI as the one that performed the action.
   */
  on_behalf_of_user_remote_id?: string | undefined;
};

/**
 * Additional fields that we will pass through to specific ATS systems.
 */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields = {
  /**
   * Fields specific to Greenhouse.
   */
  greenhouse?:
    | PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse
    | undefined;
  /**
   * Workable specific remote fields for ATS actions.
   */
  workable?:
    | PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable
    | undefined;
};

export type PostAtsCandidatesCandidateIdAttachmentsRequestBody = {
  attachment: PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment;
  /**
   * Additional fields that we will pass through to specific ATS systems.
   */
  remote_fields?:
    | PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$inboundSchema:
  z.ZodNativeEnum<
    typeof PostAtsCandidatesCandidateIdAttachmentsRequestBodyType
  > = z.nativeEnum(PostAtsCandidatesCandidateIdAttachmentsRequestBodyType);

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostAtsCandidatesCandidateIdAttachmentsRequestBodyType
  > = PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$outboundSchema;
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    content_type: z.string().optional(),
    data_url: z.string().optional(),
    data: z.string().optional(),
    type: PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$inboundSchema,
  });

/** @internal */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$Outbound =
  {
    name: string;
    content_type?: string | undefined;
    data_url?: string | undefined;
    data?: string | undefined;
    type: string;
  };

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment
  > = z.object({
    name: z.string(),
    content_type: z.string().optional(),
    data_url: z.string().optional(),
    data: z.string().optional(),
    type: PostAtsCandidatesCandidateIdAttachmentsRequestBodyType$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$Outbound;
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyAttachmentToJSON(
  postAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment:
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$outboundSchema
      .parse(postAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment),
  );
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyAttachmentFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders,
    z.ZodTypeDef,
    unknown
  > = z.object({
    "On-Behalf-Of": z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "On-Behalf-Of": "on_behalf_of",
    });
  });

/** @internal */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$Outbound =
  {
    "On-Behalf-Of"?: string | null | undefined;
  };

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders
  > = z.object({
    on_behalf_of: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      on_behalf_of: "On-Behalf-Of",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$Outbound;
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeadersToJSON(
  postAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders:
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$outboundSchema
      .parse(postAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders),
  );
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeadersFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    post_headers: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$Outbound =
  {
    post_headers?:
      | PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$Outbound
      | undefined;
  };

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse
  > = z.object({
    post_headers: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyPostHeaders$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$Outbound;
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouseToJSON(
  postAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse:
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$outboundSchema
      .parse(postAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse),
  );
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable,
    z.ZodTypeDef,
    unknown
  > = z.object({
    on_behalf_of_user_remote_id: z.string().optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$Outbound =
  {
    on_behalf_of_user_remote_id?: string | undefined;
  };

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable
  > = z.object({
    on_behalf_of_user_remote_id: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$Outbound;
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyWorkableToJSON(
  postAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable:
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$outboundSchema
      .parse(postAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable),
  );
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyWorkableFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields,
    z.ZodTypeDef,
    unknown
  > = z.object({
    greenhouse: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$inboundSchema
    ).optional(),
    workable: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$Outbound =
  {
    greenhouse?:
      | PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$Outbound
      | undefined;
    workable?:
      | PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$Outbound
      | undefined;
  };

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields
  > = z.object({
    greenhouse: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyGreenhouse$outboundSchema
    ).optional(),
    workable: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyWorkable$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$Outbound;
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFieldsToJSON(
  postAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields:
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$outboundSchema
      .parse(postAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields),
  );
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFieldsFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBody$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    attachment: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$inboundSchema
    ),
    remote_fields: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdAttachmentsRequestBody$Outbound = {
  attachment:
    PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$Outbound;
  remote_fields?:
    | PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$Outbound
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsRequestBody$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsRequestBody$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdAttachmentsRequestBody
  > = z.object({
    attachment: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyAttachment$outboundSchema
    ),
    remote_fields: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBodyRemoteFields$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdAttachmentsRequestBody$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBody$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdAttachmentsRequestBody$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdAttachmentsRequestBody$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdAttachmentsRequestBody$Outbound;
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyToJSON(
  postAtsCandidatesCandidateIdAttachmentsRequestBody:
    PostAtsCandidatesCandidateIdAttachmentsRequestBody,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdAttachmentsRequestBody$outboundSchema.parse(
      postAtsCandidatesCandidateIdAttachmentsRequestBody,
    ),
  );
}

export function postAtsCandidatesCandidateIdAttachmentsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsRequestBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsRequestBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsRequestBody' from JSON`,
  );
}
