/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PostAtsCandidatesCandidateIdTagsRequestBodyTag = {
  /**
   * The name of the tag you would like to add. We will automatically find the matching ID of the tag in the system.
   */
  name: string;
};

/**
 * Headers we will pass with `POST` requests to Greenhouse.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders = {
  /**
   * ID of the the user that will show up as having performed the action in Greenhouse. We already pass a value by default, but you can use this to override it.
   */
  on_behalf_of?: string | null | undefined;
};

/**
 * Fields specific to Greenhouse.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse = {
  /**
   * Headers we will pass with `POST` requests to Greenhouse.
   */
  post_headers?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders
    | undefined;
};

/**
 * Workable specific remote fields for ATS actions.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyWorkable = {
  /**
   * The remote ID of the user that will be displayed in the UI as the one that performed the action.
   */
  on_behalf_of_user_remote_id?: string | undefined;
};

/**
 * Additional fields that we will pass through to specific ATS systems.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields = {
  /**
   * Fields specific to Greenhouse.
   */
  greenhouse?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse
    | undefined;
  /**
   * Workable specific remote fields for ATS actions.
   */
  workable?: PostAtsCandidatesCandidateIdTagsRequestBodyWorkable | undefined;
};

export type PostAtsCandidatesCandidateIdTagsRequestBody = {
  tag: PostAtsCandidatesCandidateIdTagsRequestBodyTag;
  /**
   * Additional fields that we will pass through to specific ATS systems.
   */
  remote_fields?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyTag$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyTag,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound = {
  name: string;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyTag
  > = z.object({
    name: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdTagsRequestBodyTag$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyTag$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyTag$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound;
}

export function postAtsCandidatesCandidateIdTagsRequestBodyTagToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyTag:
    PostAtsCandidatesCandidateIdTagsRequestBodyTag,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyTag,
    ),
  );
}

export function postAtsCandidatesCandidateIdTagsRequestBodyTagFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdTagsRequestBodyTag,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdTagsRequestBodyTag$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesCandidateIdTagsRequestBodyTag' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders,
    z.ZodTypeDef,
    unknown
  > = z.object({
    "On-Behalf-Of": z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "On-Behalf-Of": "on_behalf_of",
    });
  });

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound = {
  "On-Behalf-Of"?: string | null | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders
  > = z.object({
    on_behalf_of: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      on_behalf_of: "On-Behalf-Of",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound;
}

export function postAtsCandidatesCandidateIdTagsRequestBodyPostHeadersToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyPostHeaders:
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyPostHeaders,
    ),
  );
}

export function postAtsCandidatesCandidateIdTagsRequestBodyPostHeadersFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    post_headers: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound = {
  post_headers?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse
  > = z.object({
    post_headers: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound;
}

export function postAtsCandidatesCandidateIdTagsRequestBodyGreenhouseToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyGreenhouse:
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyGreenhouse,
    ),
  );
}

export function postAtsCandidatesCandidateIdTagsRequestBodyGreenhouseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable,
    z.ZodTypeDef,
    unknown
  > = z.object({
    on_behalf_of_user_remote_id: z.string().optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound = {
  on_behalf_of_user_remote_id?: string | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable
  > = z.object({
    on_behalf_of_user_remote_id: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound;
}

export function postAtsCandidatesCandidateIdTagsRequestBodyWorkableToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyWorkable:
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyWorkable,
    ),
  );
}

export function postAtsCandidatesCandidateIdTagsRequestBodyWorkableFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdTagsRequestBodyWorkable,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesCandidateIdTagsRequestBodyWorkable' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields,
    z.ZodTypeDef,
    unknown
  > = z.object({
    greenhouse: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$inboundSchema
    ).optional(),
    workable: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound = {
  greenhouse?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound
    | undefined;
  workable?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields
  > = z.object({
    greenhouse: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema
    ).optional(),
    workable: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound` instead. */
  export type Outbound =
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound;
}

export function postAtsCandidatesCandidateIdTagsRequestBodyRemoteFieldsToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyRemoteFields:
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema
      .parse(postAtsCandidatesCandidateIdTagsRequestBodyRemoteFields),
  );
}

export function postAtsCandidatesCandidateIdTagsRequestBodyRemoteFieldsFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBody$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    tag: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyTag$inboundSchema
    ),
    remote_fields: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$inboundSchema
    ).optional(),
  });

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBody$Outbound = {
  tag: PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound;
  remote_fields?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBody$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBody$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBody
  > = z.object({
    tag: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema
    ),
    remote_fields: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema
    ).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAtsCandidatesCandidateIdTagsRequestBody$ {
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBody$inboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostAtsCandidatesCandidateIdTagsRequestBody$outboundSchema;
  /** @deprecated use `PostAtsCandidatesCandidateIdTagsRequestBody$Outbound` instead. */
  export type Outbound = PostAtsCandidatesCandidateIdTagsRequestBody$Outbound;
}

export function postAtsCandidatesCandidateIdTagsRequestBodyToJSON(
  postAtsCandidatesCandidateIdTagsRequestBody:
    PostAtsCandidatesCandidateIdTagsRequestBody,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBody$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBody,
    ),
  );
}

export function postAtsCandidatesCandidateIdTagsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdTagsRequestBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdTagsRequestBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostAtsCandidatesCandidateIdTagsRequestBody' from JSON`,
  );
}
