/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PostAtsCandidatesCandidateIdResultLinksPositiveResponseData = {};

export type PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning = {
  message: string;
};

export type PostAtsCandidatesCandidateIdResultLinksPositiveResponse = {
  status: "success";
  data: PostAtsCandidatesCandidateIdResultLinksPositiveResponseData;
  /**
   * These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
   */
  warnings: Array<
    PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning
  >;
};

/** @internal */
export const PostAtsCandidatesCandidateIdResultLinksPositiveResponseData$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdResultLinksPositiveResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function postAtsCandidatesCandidateIdResultLinksPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdResultLinksPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdResultLinksPositiveResponseData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdResultLinksPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

export function postAtsCandidatesCandidateIdResultLinksPositiveResponseWarningFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdResultLinksPositiveResponse$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdResultLinksPositiveResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      PostAtsCandidatesCandidateIdResultLinksPositiveResponseData$inboundSchema
    ),
    warnings: z.array(
      z.lazy(() =>
        PostAtsCandidatesCandidateIdResultLinksPositiveResponseWarning$inboundSchema
      ),
    ),
  });

export function postAtsCandidatesCandidateIdResultLinksPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdResultLinksPositiveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdResultLinksPositiveResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdResultLinksPositiveResponse' from JSON`,
  );
}
