/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type PostAtsCandidatesCandidateIdTagsRequestBodyTag = {
  /**
   * The name of the tag you would like to add. We will automatically find the matching ID of the tag in the system.
   */
  name: string;
};

/**
 * Headers we will pass with `POST` requests to Greenhouse.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders = {
  /**
   * ID of the the user that will show up as having performed the action in Greenhouse. We already pass a value by default, but you can use this to override it.
   */
  on_behalf_of?: string | null | undefined;
};

/**
 * Fields specific to Greenhouse.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse = {
  /**
   * Headers we will pass with `POST` requests to Greenhouse.
   */
  post_headers?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders
    | undefined;
};

/**
 * Workable specific remote fields for ATS actions.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyWorkable = {
  /**
   * The remote ID of the user that will be displayed in the UI as the one that performed the action.
   */
  on_behalf_of_user_remote_id?: string | undefined;
};

/**
 * Additional fields that we will pass through to specific ATS systems.
 */
export type PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields = {
  /**
   * Fields specific to Greenhouse.
   */
  greenhouse?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse
    | undefined;
  /**
   * Workable specific remote fields for ATS actions.
   */
  workable?: PostAtsCandidatesCandidateIdTagsRequestBodyWorkable | undefined;
};

export type PostAtsCandidatesCandidateIdTagsRequestBody = {
  tag: PostAtsCandidatesCandidateIdTagsRequestBodyTag;
  /**
   * Additional fields that we will pass through to specific ATS systems.
   */
  remote_fields?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields
    | undefined;
};

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound = {
  name: string;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyTag
  > = z.object({
    name: z.string(),
  });

export function postAtsCandidatesCandidateIdTagsRequestBodyTagToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyTag:
    PostAtsCandidatesCandidateIdTagsRequestBodyTag,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyTag,
    ),
  );
}

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound = {
  "On-Behalf-Of"?: string | null | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders
  > = z.object({
    on_behalf_of: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      on_behalf_of: "On-Behalf-Of",
    });
  });

export function postAtsCandidatesCandidateIdTagsRequestBodyPostHeadersToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyPostHeaders:
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyPostHeaders,
    ),
  );
}

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound = {
  post_headers?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$Outbound
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse
  > = z.object({
    post_headers: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyPostHeaders$outboundSchema
    ).optional(),
  });

export function postAtsCandidatesCandidateIdTagsRequestBodyGreenhouseToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyGreenhouse:
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyGreenhouse,
    ),
  );
}

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound = {
  on_behalf_of_user_remote_id?: string | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable
  > = z.object({
    on_behalf_of_user_remote_id: z.string().optional(),
  });

export function postAtsCandidatesCandidateIdTagsRequestBodyWorkableToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyWorkable:
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBodyWorkable,
    ),
  );
}

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound = {
  greenhouse?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$Outbound
    | undefined;
  workable?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$Outbound
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields
  > = z.object({
    greenhouse: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyGreenhouse$outboundSchema
    ).optional(),
    workable: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyWorkable$outboundSchema
    ).optional(),
  });

export function postAtsCandidatesCandidateIdTagsRequestBodyRemoteFieldsToJSON(
  postAtsCandidatesCandidateIdTagsRequestBodyRemoteFields:
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema
      .parse(postAtsCandidatesCandidateIdTagsRequestBodyRemoteFields),
  );
}

/** @internal */
export type PostAtsCandidatesCandidateIdTagsRequestBody$Outbound = {
  tag: PostAtsCandidatesCandidateIdTagsRequestBodyTag$Outbound;
  remote_fields?:
    | PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$Outbound
    | undefined;
};

/** @internal */
export const PostAtsCandidatesCandidateIdTagsRequestBody$outboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdTagsRequestBody$Outbound,
    z.ZodTypeDef,
    PostAtsCandidatesCandidateIdTagsRequestBody
  > = z.object({
    tag: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyTag$outboundSchema
    ),
    remote_fields: z.lazy(() =>
      PostAtsCandidatesCandidateIdTagsRequestBodyRemoteFields$outboundSchema
    ).optional(),
  });

export function postAtsCandidatesCandidateIdTagsRequestBodyToJSON(
  postAtsCandidatesCandidateIdTagsRequestBody:
    PostAtsCandidatesCandidateIdTagsRequestBody,
): string {
  return JSON.stringify(
    PostAtsCandidatesCandidateIdTagsRequestBody$outboundSchema.parse(
      postAtsCandidatesCandidateIdTagsRequestBody,
    ),
  );
}
