/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData = {};

export type PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning = {
  message: string;
};

export type PostHrisEmployeesEmployeeIdDocumentsPositiveResponse = {
  status: "success";
  data: PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData;
  /**
   * These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
   */
  warnings: Array<PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning>;
};

/** @internal */
export const PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData$inboundSchema:
  z.ZodType<
    PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function postHrisEmployeesEmployeeIdDocumentsPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning$inboundSchema:
  z.ZodType<
    PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

export function postHrisEmployeesEmployeeIdDocumentsPositiveResponseWarningFromJSON(
  jsonString: string,
): SafeParseResult<
  PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning' from JSON`,
  );
}

/** @internal */
export const PostHrisEmployeesEmployeeIdDocumentsPositiveResponse$inboundSchema:
  z.ZodType<
    PostHrisEmployeesEmployeeIdDocumentsPositiveResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      PostHrisEmployeesEmployeeIdDocumentsPositiveResponseData$inboundSchema
    ),
    warnings: z.array(
      z.lazy(() =>
        PostHrisEmployeesEmployeeIdDocumentsPositiveResponseWarning$inboundSchema
      ),
    ),
  });

export function postHrisEmployeesEmployeeIdDocumentsPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostHrisEmployeesEmployeeIdDocumentsPositiveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostHrisEmployeesEmployeeIdDocumentsPositiveResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostHrisEmployeesEmployeeIdDocumentsPositiveResponse' from JSON`,
  );
}
