/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PostAtsApplicationsApplicationIdRejectPositiveResponseData = {};

export type PostAtsApplicationsApplicationIdRejectPositiveResponseWarning = {
  message: string;
};

export type PostAtsApplicationsApplicationIdRejectPositiveResponse = {
  status: "success";
  data: PostAtsApplicationsApplicationIdRejectPositiveResponseData;
  /**
   * These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
   */
  warnings: Array<
    PostAtsApplicationsApplicationIdRejectPositiveResponseWarning
  >;
};

/** @internal */
export const PostAtsApplicationsApplicationIdRejectPositiveResponseData$inboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdRejectPositiveResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function postAtsApplicationsApplicationIdRejectPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsApplicationsApplicationIdRejectPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsApplicationsApplicationIdRejectPositiveResponseData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsApplicationsApplicationIdRejectPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const PostAtsApplicationsApplicationIdRejectPositiveResponseWarning$inboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdRejectPositiveResponseWarning,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

export function postAtsApplicationsApplicationIdRejectPositiveResponseWarningFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsApplicationsApplicationIdRejectPositiveResponseWarning,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsApplicationsApplicationIdRejectPositiveResponseWarning$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsApplicationsApplicationIdRejectPositiveResponseWarning' from JSON`,
  );
}

/** @internal */
export const PostAtsApplicationsApplicationIdRejectPositiveResponse$inboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdRejectPositiveResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      PostAtsApplicationsApplicationIdRejectPositiveResponseData$inboundSchema
    ),
    warnings: z.array(
      z.lazy(() =>
        PostAtsApplicationsApplicationIdRejectPositiveResponseWarning$inboundSchema
      ),
    ),
  });

export function postAtsApplicationsApplicationIdRejectPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsApplicationsApplicationIdRejectPositiveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsApplicationsApplicationIdRejectPositiveResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsApplicationsApplicationIdRejectPositiveResponse' from JSON`,
  );
}
