/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
 */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyType = {
  Cv: "CV",
  CoverLetter: "COVER_LETTER",
  Other: "OTHER",
} as const;
/**
 * Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
 */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyType =
  ClosedEnum<typeof PostAtsApplicationsApplicationIdAttachmentsRequestBodyType>;

export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment = {
  /**
   * File name of the file you want to upload. We recommend providing something human-readable with a valid file extension (like `Resume.pdf`), as this might be shown in your customer's system.
   */
  name: string;
  /**
   * Content/MIME type of the file (e.g., `application/pdf`).
   *
   * @remarks
   *
   * If you provide `data`, this is required. If you provide `data_url`, this is optional and we'll attempt to use the `Content-Type` header of the response.
   *
   * **Note:** Please validate that the content type you provide is actually meaningful (and not something generic like [`application/octet-stream`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types#applicationoctet-stream)). Especially when using object storage (like AWS S3), it's easy to accidentally discard the content types of user-provided files, so make sure to explicitly persist them when processing uploads from your users (see guides for [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#SysMetadata), [Google Cloud](https://cloud.google.com/storage/docs/metadata#content-type), and [Azure](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-all-blob-types)).
   */
  content_type?: string | undefined;
  /**
   * URL to the file you want to upload that can be accessed without authentication headers. We will download the content immediately when receiving the request, so the URL can be short-lived.
   *
   * @remarks
   *
   * If you're using an object storage provider (like AWS S3), we strongly recommend providing a signed URL for secure access (see guides for [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html), [Google Cloud](https://cloud.google.com/storage/docs/access-control/signed-urls), and [Azure](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview)).
   *
   * **Note:** You must provide either this or `data_url`. We recommend `data_url` over `data` for most cases.
   */
  data_url?: string | undefined;
  /**
   * Base64-encoded contents of the file you want to upload.
   *
   * @remarks
   *
   * **Note:** You must provide either this or `data_url`. We recommend `data_url` over `data` for most cases.
   */
  data?: string | undefined;
  /**
   * Type of the attachment in the ATS. This may affect where the uploaded file will be shown in your customer's system.
   */
  type: PostAtsApplicationsApplicationIdAttachmentsRequestBodyType;
};

/**
 * Allows you to override the document category for the attachment.
 */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory =
  {
    IrcCandidateResume: "IRC_CANDIDATE_RESUME",
    IrcCandidateCoverletter: "IRC_CANDIDATE_COVERLETTER",
    Misc: "MISC",
    IrcInternal: "IRC_INTERNAL",
  } as const;
/**
 * Allows you to override the document category for the attachment.
 */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory =
  ClosedEnum<
    typeof PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory
  >;

/**
 * Oracle specific remote fields for the attachment.
 */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle = {
  /**
   * Allows you to override the document category for the attachment.
   */
  override_document_category?:
    | PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory
    | undefined;
  /**
   * If true, the attachment will be posted to all current applications for the candidate.
   */
  multi_post_to_all_current_applications?: boolean | undefined;
};

/**
 * Headers we will pass with `POST` requests to Greenhouse.
 */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders =
  {
    /**
     * ID of the the user that will show up as having performed the action in Greenhouse. We already pass a value by default, but you can use this to override it.
     */
    on_behalf_of?: string | null | undefined;
  };

/**
 * Fields specific to Greenhouse.
 */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse = {
  /**
   * Headers we will pass with `POST` requests to Greenhouse.
   */
  post_headers?:
    | PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders
    | undefined;
};

/**
 * Workable specific remote fields for ATS actions.
 */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable = {
  /**
   * The remote ID of the user that will be displayed in the UI as the one that performed the action.
   */
  on_behalf_of_user_remote_id?: string | undefined;
};

/**
 * Additional fields that we will pass through to specific ATS systems.
 */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields =
  {
    /**
     * Oracle specific remote fields for the attachment.
     */
    oracle?:
      | PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle
      | undefined;
    /**
     * Fields specific to Greenhouse.
     */
    greenhouse?:
      | PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse
      | undefined;
    /**
     * Workable specific remote fields for ATS actions.
     */
    workable?:
      | PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable
      | undefined;
  };

export type PostAtsApplicationsApplicationIdAttachmentsRequestBody = {
  attachment: PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment;
  remote_fields?:
    | PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields
    | undefined;
};

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostAtsApplicationsApplicationIdAttachmentsRequestBodyType
  > = z.nativeEnum(PostAtsApplicationsApplicationIdAttachmentsRequestBodyType);

/** @internal */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment$Outbound =
  {
    name: string;
    content_type?: string | undefined;
    data_url?: string | undefined;
    data?: string | undefined;
    type: string;
  };

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment$outboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment$Outbound,
    z.ZodTypeDef,
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment
  > = z.object({
    name: z.string(),
    content_type: z.string().optional(),
    data_url: z.string().optional(),
    data: z.string().optional(),
    type:
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyType$outboundSchema,
  });

export function postAtsApplicationsApplicationIdAttachmentsRequestBodyAttachmentToJSON(
  postAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment:
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment,
): string {
  return JSON.stringify(
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment$outboundSchema
      .parse(postAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment),
  );
}

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory$outboundSchema:
  z.ZodNativeEnum<
    typeof PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory
  > = z.nativeEnum(
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory,
  );

/** @internal */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle$Outbound =
  {
    override_document_category?: string | undefined;
    multi_post_to_all_current_applications?: boolean | undefined;
  };

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle$outboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle$Outbound,
    z.ZodTypeDef,
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle
  > = z.object({
    override_document_category:
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyOverrideDocumentCategory$outboundSchema
        .optional(),
    multi_post_to_all_current_applications: z.boolean().optional(),
  });

export function postAtsApplicationsApplicationIdAttachmentsRequestBodyOracleToJSON(
  postAtsApplicationsApplicationIdAttachmentsRequestBodyOracle:
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle,
): string {
  return JSON.stringify(
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle$outboundSchema
      .parse(postAtsApplicationsApplicationIdAttachmentsRequestBodyOracle),
  );
}

/** @internal */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders$Outbound =
  {
    "On-Behalf-Of"?: string | null | undefined;
  };

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders$outboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders$Outbound,
    z.ZodTypeDef,
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders
  > = z.object({
    on_behalf_of: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      on_behalf_of: "On-Behalf-Of",
    });
  });

export function postAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeadersToJSON(
  postAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders:
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders,
): string {
  return JSON.stringify(
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders$outboundSchema
      .parse(postAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders),
  );
}

/** @internal */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse$Outbound =
  {
    post_headers?:
      | PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders$Outbound
      | undefined;
  };

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse$outboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse$Outbound,
    z.ZodTypeDef,
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse
  > = z.object({
    post_headers: z.lazy(() =>
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyPostHeaders$outboundSchema
    ).optional(),
  });

export function postAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouseToJSON(
  postAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse:
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse,
): string {
  return JSON.stringify(
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse$outboundSchema
      .parse(postAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse),
  );
}

/** @internal */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable$Outbound =
  {
    on_behalf_of_user_remote_id?: string | undefined;
  };

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable$outboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable$Outbound,
    z.ZodTypeDef,
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable
  > = z.object({
    on_behalf_of_user_remote_id: z.string().optional(),
  });

export function postAtsApplicationsApplicationIdAttachmentsRequestBodyWorkableToJSON(
  postAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable:
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable,
): string {
  return JSON.stringify(
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable$outboundSchema
      .parse(postAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable),
  );
}

/** @internal */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields$Outbound =
  {
    oracle?:
      | PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle$Outbound
      | undefined;
    greenhouse?:
      | PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse$Outbound
      | undefined;
    workable?:
      | PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable$Outbound
      | undefined;
  };

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields$outboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields$Outbound,
    z.ZodTypeDef,
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields
  > = z.object({
    oracle: z.lazy(() =>
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyOracle$outboundSchema
    ).optional(),
    greenhouse: z.lazy(() =>
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyGreenhouse$outboundSchema
    ).optional(),
    workable: z.lazy(() =>
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyWorkable$outboundSchema
    ).optional(),
  });

export function postAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFieldsToJSON(
  postAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields:
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields,
): string {
  return JSON.stringify(
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields$outboundSchema
      .parse(
        postAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields,
      ),
  );
}

/** @internal */
export type PostAtsApplicationsApplicationIdAttachmentsRequestBody$Outbound = {
  attachment:
    PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment$Outbound;
  remote_fields?:
    | PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields$Outbound
    | undefined;
};

/** @internal */
export const PostAtsApplicationsApplicationIdAttachmentsRequestBody$outboundSchema:
  z.ZodType<
    PostAtsApplicationsApplicationIdAttachmentsRequestBody$Outbound,
    z.ZodTypeDef,
    PostAtsApplicationsApplicationIdAttachmentsRequestBody
  > = z.object({
    attachment: z.lazy(() =>
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyAttachment$outboundSchema
    ),
    remote_fields: z.lazy(() =>
      PostAtsApplicationsApplicationIdAttachmentsRequestBodyRemoteFields$outboundSchema
    ).optional(),
  });

export function postAtsApplicationsApplicationIdAttachmentsRequestBodyToJSON(
  postAtsApplicationsApplicationIdAttachmentsRequestBody:
    PostAtsApplicationsApplicationIdAttachmentsRequestBody,
): string {
  return JSON.stringify(
    PostAtsApplicationsApplicationIdAttachmentsRequestBody$outboundSchema.parse(
      postAtsApplicationsApplicationIdAttachmentsRequestBody,
    ),
  );
}
