/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData = {};

export type PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning = {
  message: string;
};

export type PostAtsCandidatesCandidateIdAttachmentsPositiveResponse = {
  status: "success";
  data: PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData;
  /**
   * These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
   */
  warnings: Array<
    PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning
  >;
};

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function postAtsCandidatesCandidateIdAttachmentsPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

export function postAtsCandidatesCandidateIdAttachmentsPositiveResponseWarningFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning' from JSON`,
  );
}

/** @internal */
export const PostAtsCandidatesCandidateIdAttachmentsPositiveResponse$inboundSchema:
  z.ZodType<
    PostAtsCandidatesCandidateIdAttachmentsPositiveResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: z.literal("success"),
    data: z.lazy(() =>
      PostAtsCandidatesCandidateIdAttachmentsPositiveResponseData$inboundSchema
    ),
    warnings: z.array(
      z.lazy(() =>
        PostAtsCandidatesCandidateIdAttachmentsPositiveResponseWarning$inboundSchema
      ),
    ),
  });

export function postAtsCandidatesCandidateIdAttachmentsPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostAtsCandidatesCandidateIdAttachmentsPositiveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostAtsCandidatesCandidateIdAttachmentsPositiveResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostAtsCandidatesCandidateIdAttachmentsPositiveResponse' from JSON`,
  );
}
