/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The unit of time for this absence. Can be `HOURS` or `DAYS`.
 */
export const PostHrisAbsencesPositiveResponseUnit = {
  Hours: "HOURS",
  Days: "DAYS",
} as const;
/**
 * The unit of time for this absence. Can be `HOURS` or `DAYS`.
 */
export type PostHrisAbsencesPositiveResponseUnit = ClosedEnum<
  typeof PostHrisAbsencesPositiveResponseUnit
>;

export const PostHrisAbsencesPositiveResponseStatus = {
  Requested: "REQUESTED",
  Approved: "APPROVED",
  Declined: "DECLINED",
  Cancelled: "CANCELLED",
  Deleted: "DELETED",
} as const;
export type PostHrisAbsencesPositiveResponseStatus = OpenEnum<
  typeof PostHrisAbsencesPositiveResponseStatus
>;

export type PostHrisAbsencesPositiveResponseData = {
  /**
   * The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
   */
  id: string;
  /**
   * The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
   */
  remote_id: string | null;
  /**
   * The Kombo ID of the employee to which the absence belongs to. The ID can be used to retrieve the employee from the `get employees` endpoint.
   */
  employee_id: string;
  /**
   * The date this absence starts in the `yyyy-MM-dd` format.
   */
  start_date?: any | null | undefined;
  /**
   * The date this absence ends in the `yyyy-MM-dd` format.
   */
  end_date?: any | null | undefined;
  /**
   * `true` if the absence starts in the middle of the day, `false` if not, and `null` if the absence type doesn't support half-day absences. For multi-day absences, this only applies to the first day of the absence.
   */
  start_half_day: boolean | null;
  /**
   * `true` if the absence ends in the middle of the day, `false` if not, and `null` if the absence type doesn't support half-day absences. For multi-day absences, this only applies to the last day of the absence.
   */
  end_half_day: boolean | null;
  /**
   * The time at which this absence starts. Follows the format `HH:mm:ss` (e.g., `14:45:15`).
   */
  start_time?: any | null | undefined;
  /**
   * The time at which this absence ends. Follows the format `HH:mm:ss` (e.g., `14:45:15`).
   */
  end_time?: any | null | undefined;
  /**
   * The amount of time this absence takes.
   */
  amount: number | null;
  /**
   * The unit of time for this absence. Can be `HOURS` or `DAYS`.
   */
  unit: PostHrisAbsencesPositiveResponseUnit | null;
  /**
   * The absence’s current status. In rare cases where we can’t find a clear mapping, the original string is passed through.
   */
  status?: PostHrisAbsencesPositiveResponseStatus | null | undefined;
  /**
   * A note the employee has added to this absence.
   */
  employee_note: string | null;
  /**
   * The Kombo absence type ID of this absence.
   */
  type_id: string | null;
  /**
   * The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
   */
  changed_at: Date;
  /**
   * The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
   */
  remote_deleted_at: Date | null;
};

export type PostHrisAbsencesPositiveResponseWarning = {
  message: string;
};

export type PostHrisAbsencesPositiveResponse = {
  status: "success";
  data: PostHrisAbsencesPositiveResponseData;
  /**
   * These are the interaction warnings that are shown in the dashboard. They are meant to provide debug information to you. We recommend logging them to the console.
   */
  warnings: Array<PostHrisAbsencesPositiveResponseWarning>;
};

/** @internal */
export const PostHrisAbsencesPositiveResponseUnit$inboundSchema:
  z.ZodNativeEnum<typeof PostHrisAbsencesPositiveResponseUnit> = z.nativeEnum(
    PostHrisAbsencesPositiveResponseUnit,
  );

/** @internal */
export const PostHrisAbsencesPositiveResponseStatus$inboundSchema: z.ZodType<
  PostHrisAbsencesPositiveResponseStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PostHrisAbsencesPositiveResponseStatus);

/** @internal */
export const PostHrisAbsencesPositiveResponseData$inboundSchema: z.ZodType<
  PostHrisAbsencesPositiveResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  remote_id: z.nullable(z.string()),
  employee_id: z.string(),
  start_date: z.nullable(z.any()).optional(),
  end_date: z.nullable(z.any()).optional(),
  start_half_day: z.nullable(z.boolean()),
  end_half_day: z.nullable(z.boolean()),
  start_time: z.nullable(z.any()).optional(),
  end_time: z.nullable(z.any()).optional(),
  amount: z.nullable(z.number()),
  unit: z.nullable(PostHrisAbsencesPositiveResponseUnit$inboundSchema),
  status: z.nullable(PostHrisAbsencesPositiveResponseStatus$inboundSchema)
    .optional(),
  employee_note: z.nullable(z.string()),
  type_id: z.nullable(z.string()),
  changed_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  remote_deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
});

export function postHrisAbsencesPositiveResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PostHrisAbsencesPositiveResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostHrisAbsencesPositiveResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostHrisAbsencesPositiveResponseData' from JSON`,
  );
}

/** @internal */
export const PostHrisAbsencesPositiveResponseWarning$inboundSchema: z.ZodType<
  PostHrisAbsencesPositiveResponseWarning,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

export function postHrisAbsencesPositiveResponseWarningFromJSON(
  jsonString: string,
): SafeParseResult<
  PostHrisAbsencesPositiveResponseWarning,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostHrisAbsencesPositiveResponseWarning$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostHrisAbsencesPositiveResponseWarning' from JSON`,
  );
}

/** @internal */
export const PostHrisAbsencesPositiveResponse$inboundSchema: z.ZodType<
  PostHrisAbsencesPositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("success"),
  data: z.lazy(() => PostHrisAbsencesPositiveResponseData$inboundSchema),
  warnings: z.array(
    z.lazy(() => PostHrisAbsencesPositiveResponseWarning$inboundSchema),
  ),
});

export function postHrisAbsencesPositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostHrisAbsencesPositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostHrisAbsencesPositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostHrisAbsencesPositiveResponse' from JSON`,
  );
}
