/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const PutAssessmentPackagesRequestBodyType = {
  Behavioral: "BEHAVIORAL",
  VideoInterview: "VIDEO_INTERVIEW",
  SkillsTest: "SKILLS_TEST",
  BackgroundCheck: "BACKGROUND_CHECK",
  ReferenceCheck: "REFERENCE_CHECK",
} as const;
export type PutAssessmentPackagesRequestBodyType = ClosedEnum<
  typeof PutAssessmentPackagesRequestBodyType
>;

export type PutAssessmentPackagesRequestBodyPackage = {
  /**
   * A unique identifier for the assessment package.
   */
  id: string;
  type: PutAssessmentPackagesRequestBodyType;
  /**
   * The name of the assessment package.
   */
  name: string;
  /**
   * Description about the package. Some ATSs will display this in their UI.
   */
  description: string;
};

export type PutAssessmentPackagesRequestBody = {
  packages: Array<PutAssessmentPackagesRequestBodyPackage>;
};

/** @internal */
export const PutAssessmentPackagesRequestBodyType$inboundSchema:
  z.ZodNativeEnum<typeof PutAssessmentPackagesRequestBodyType> = z.nativeEnum(
    PutAssessmentPackagesRequestBodyType,
  );

/** @internal */
export const PutAssessmentPackagesRequestBodyType$outboundSchema:
  z.ZodNativeEnum<typeof PutAssessmentPackagesRequestBodyType> =
    PutAssessmentPackagesRequestBodyType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutAssessmentPackagesRequestBodyType$ {
  /** @deprecated use `PutAssessmentPackagesRequestBodyType$inboundSchema` instead. */
  export const inboundSchema =
    PutAssessmentPackagesRequestBodyType$inboundSchema;
  /** @deprecated use `PutAssessmentPackagesRequestBodyType$outboundSchema` instead. */
  export const outboundSchema =
    PutAssessmentPackagesRequestBodyType$outboundSchema;
}

/** @internal */
export const PutAssessmentPackagesRequestBodyPackage$inboundSchema: z.ZodType<
  PutAssessmentPackagesRequestBodyPackage,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: PutAssessmentPackagesRequestBodyType$inboundSchema,
  name: z.string(),
  description: z.string(),
});

/** @internal */
export type PutAssessmentPackagesRequestBodyPackage$Outbound = {
  id: string;
  type: string;
  name: string;
  description: string;
};

/** @internal */
export const PutAssessmentPackagesRequestBodyPackage$outboundSchema: z.ZodType<
  PutAssessmentPackagesRequestBodyPackage$Outbound,
  z.ZodTypeDef,
  PutAssessmentPackagesRequestBodyPackage
> = z.object({
  id: z.string(),
  type: PutAssessmentPackagesRequestBodyType$outboundSchema,
  name: z.string(),
  description: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutAssessmentPackagesRequestBodyPackage$ {
  /** @deprecated use `PutAssessmentPackagesRequestBodyPackage$inboundSchema` instead. */
  export const inboundSchema =
    PutAssessmentPackagesRequestBodyPackage$inboundSchema;
  /** @deprecated use `PutAssessmentPackagesRequestBodyPackage$outboundSchema` instead. */
  export const outboundSchema =
    PutAssessmentPackagesRequestBodyPackage$outboundSchema;
  /** @deprecated use `PutAssessmentPackagesRequestBodyPackage$Outbound` instead. */
  export type Outbound = PutAssessmentPackagesRequestBodyPackage$Outbound;
}

export function putAssessmentPackagesRequestBodyPackageToJSON(
  putAssessmentPackagesRequestBodyPackage:
    PutAssessmentPackagesRequestBodyPackage,
): string {
  return JSON.stringify(
    PutAssessmentPackagesRequestBodyPackage$outboundSchema.parse(
      putAssessmentPackagesRequestBodyPackage,
    ),
  );
}

export function putAssessmentPackagesRequestBodyPackageFromJSON(
  jsonString: string,
): SafeParseResult<
  PutAssessmentPackagesRequestBodyPackage,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutAssessmentPackagesRequestBodyPackage$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutAssessmentPackagesRequestBodyPackage' from JSON`,
  );
}

/** @internal */
export const PutAssessmentPackagesRequestBody$inboundSchema: z.ZodType<
  PutAssessmentPackagesRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  packages: z.array(
    z.lazy(() => PutAssessmentPackagesRequestBodyPackage$inboundSchema),
  ),
});

/** @internal */
export type PutAssessmentPackagesRequestBody$Outbound = {
  packages: Array<PutAssessmentPackagesRequestBodyPackage$Outbound>;
};

/** @internal */
export const PutAssessmentPackagesRequestBody$outboundSchema: z.ZodType<
  PutAssessmentPackagesRequestBody$Outbound,
  z.ZodTypeDef,
  PutAssessmentPackagesRequestBody
> = z.object({
  packages: z.array(
    z.lazy(() => PutAssessmentPackagesRequestBodyPackage$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutAssessmentPackagesRequestBody$ {
  /** @deprecated use `PutAssessmentPackagesRequestBody$inboundSchema` instead. */
  export const inboundSchema = PutAssessmentPackagesRequestBody$inboundSchema;
  /** @deprecated use `PutAssessmentPackagesRequestBody$outboundSchema` instead. */
  export const outboundSchema = PutAssessmentPackagesRequestBody$outboundSchema;
  /** @deprecated use `PutAssessmentPackagesRequestBody$Outbound` instead. */
  export type Outbound = PutAssessmentPackagesRequestBody$Outbound;
}

export function putAssessmentPackagesRequestBodyToJSON(
  putAssessmentPackagesRequestBody: PutAssessmentPackagesRequestBody,
): string {
  return JSON.stringify(
    PutAssessmentPackagesRequestBody$outboundSchema.parse(
      putAssessmentPackagesRequestBody,
    ),
  );
}

export function putAssessmentPackagesRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PutAssessmentPackagesRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutAssessmentPackagesRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutAssessmentPackagesRequestBody' from JSON`,
  );
}
