/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Headers we will pass with `POST` requests to Greenhouse.
 */
export type PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders = {
  /**
   * ID of the the user that will show up as having performed the action in Greenhouse. We already pass a value by default, but you can use this to override it.
   */
  on_behalf_of?: string | null | undefined;
};

/**
 * Fields specific to Greenhouse.
 */
export type PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse = {
  /**
   * Headers we will pass with `POST` requests to Greenhouse.
   */
  post_headers?:
    | PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders
    | undefined;
};

/**
 * Workable specific remote fields for ATS actions.
 */
export type PutAtsApplicationsApplicationIdStageRequestBodyWorkable = {
  /**
   * The remote ID of the user that will be displayed in the UI as the one that performed the action.
   */
  on_behalf_of_user_remote_id?: string | undefined;
};

/**
 * Additional fields that we will pass through to specific ATS systems.
 */
export type PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields = {
  /**
   * Fields specific to Greenhouse.
   */
  greenhouse?:
    | PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse
    | undefined;
  /**
   * Workable specific remote fields for ATS actions.
   */
  workable?:
    | PutAtsApplicationsApplicationIdStageRequestBodyWorkable
    | undefined;
};

export type PutAtsApplicationsApplicationIdStageRequestBody = {
  /**
   * The Kombo ID of the stage to move the application to. This stage must be allowed for the job that the application is connected to. Get available stages from the `stages` property on the job, not from the deprecated application-stages endpoint.
   */
  stage_id: string;
  /**
   * Additional fields that we will pass through to specific ATS systems.
   */
  remote_fields?:
    | PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields
    | undefined;
};

/** @internal */
export type PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders$Outbound =
  {
    "On-Behalf-Of"?: string | null | undefined;
  };

/** @internal */
export const PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders$outboundSchema:
  z.ZodType<
    PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders$Outbound,
    z.ZodTypeDef,
    PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders
  > = z.object({
    on_behalf_of: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      on_behalf_of: "On-Behalf-Of",
    });
  });

export function putAtsApplicationsApplicationIdStageRequestBodyPostHeadersToJSON(
  putAtsApplicationsApplicationIdStageRequestBodyPostHeaders:
    PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders,
): string {
  return JSON.stringify(
    PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders$outboundSchema
      .parse(putAtsApplicationsApplicationIdStageRequestBodyPostHeaders),
  );
}

/** @internal */
export type PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse$Outbound =
  {
    post_headers?:
      | PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders$Outbound
      | undefined;
  };

/** @internal */
export const PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse$outboundSchema:
  z.ZodType<
    PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse$Outbound,
    z.ZodTypeDef,
    PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse
  > = z.object({
    post_headers: z.lazy(() =>
      PutAtsApplicationsApplicationIdStageRequestBodyPostHeaders$outboundSchema
    ).optional(),
  });

export function putAtsApplicationsApplicationIdStageRequestBodyGreenhouseToJSON(
  putAtsApplicationsApplicationIdStageRequestBodyGreenhouse:
    PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse,
): string {
  return JSON.stringify(
    PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse$outboundSchema
      .parse(putAtsApplicationsApplicationIdStageRequestBodyGreenhouse),
  );
}

/** @internal */
export type PutAtsApplicationsApplicationIdStageRequestBodyWorkable$Outbound = {
  on_behalf_of_user_remote_id?: string | undefined;
};

/** @internal */
export const PutAtsApplicationsApplicationIdStageRequestBodyWorkable$outboundSchema:
  z.ZodType<
    PutAtsApplicationsApplicationIdStageRequestBodyWorkable$Outbound,
    z.ZodTypeDef,
    PutAtsApplicationsApplicationIdStageRequestBodyWorkable
  > = z.object({
    on_behalf_of_user_remote_id: z.string().optional(),
  });

export function putAtsApplicationsApplicationIdStageRequestBodyWorkableToJSON(
  putAtsApplicationsApplicationIdStageRequestBodyWorkable:
    PutAtsApplicationsApplicationIdStageRequestBodyWorkable,
): string {
  return JSON.stringify(
    PutAtsApplicationsApplicationIdStageRequestBodyWorkable$outboundSchema
      .parse(putAtsApplicationsApplicationIdStageRequestBodyWorkable),
  );
}

/** @internal */
export type PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields$Outbound =
  {
    greenhouse?:
      | PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse$Outbound
      | undefined;
    workable?:
      | PutAtsApplicationsApplicationIdStageRequestBodyWorkable$Outbound
      | undefined;
  };

/** @internal */
export const PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields$outboundSchema:
  z.ZodType<
    PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields$Outbound,
    z.ZodTypeDef,
    PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields
  > = z.object({
    greenhouse: z.lazy(() =>
      PutAtsApplicationsApplicationIdStageRequestBodyGreenhouse$outboundSchema
    ).optional(),
    workable: z.lazy(() =>
      PutAtsApplicationsApplicationIdStageRequestBodyWorkable$outboundSchema
    ).optional(),
  });

export function putAtsApplicationsApplicationIdStageRequestBodyRemoteFieldsToJSON(
  putAtsApplicationsApplicationIdStageRequestBodyRemoteFields:
    PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields,
): string {
  return JSON.stringify(
    PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields$outboundSchema
      .parse(putAtsApplicationsApplicationIdStageRequestBodyRemoteFields),
  );
}

/** @internal */
export type PutAtsApplicationsApplicationIdStageRequestBody$Outbound = {
  stage_id: string;
  remote_fields?:
    | PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields$Outbound
    | undefined;
};

/** @internal */
export const PutAtsApplicationsApplicationIdStageRequestBody$outboundSchema:
  z.ZodType<
    PutAtsApplicationsApplicationIdStageRequestBody$Outbound,
    z.ZodTypeDef,
    PutAtsApplicationsApplicationIdStageRequestBody
  > = z.object({
    stage_id: z.string(),
    remote_fields: z.lazy(() =>
      PutAtsApplicationsApplicationIdStageRequestBodyRemoteFields$outboundSchema
    ).optional(),
  });

export function putAtsApplicationsApplicationIdStageRequestBodyToJSON(
  putAtsApplicationsApplicationIdStageRequestBody:
    PutAtsApplicationsApplicationIdStageRequestBody,
): string {
  return JSON.stringify(
    PutAtsApplicationsApplicationIdStageRequestBody$outboundSchema.parse(
      putAtsApplicationsApplicationIdStageRequestBody,
    ),
  );
}
