/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody = {
  /**
   * The integration field's unique ID which the custom field should be mapped to. Null to remove a mapping.
   */
  integration_field_id: string | null;
};

/** @internal */
export type PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody$Outbound =
  {
    integration_field_id: string | null;
  };

/** @internal */
export const PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody$outboundSchema:
  z.ZodType<
    PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody$Outbound,
    z.ZodTypeDef,
    PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody
  > = z.object({
    integration_field_id: z.nullable(z.string()),
  });

export function putIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBodyToJSON(
  putIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody:
    PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody,
): string {
  return JSON.stringify(
    PutIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody$outboundSchema
      .parse(putIntegrationsIntegrationIdCustomFieldsCustomFieldIdRequestBody),
  );
}
