/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Schema1Union2, Schema1Union2$inboundSchema } from "./schema1union2.js";
import {
  Schema2Checkbox,
  Schema2Checkbox$inboundSchema,
  Schema2Date,
  Schema2Date$inboundSchema,
  Schema2File,
  Schema2File$inboundSchema,
  Schema2MultiSelect,
  Schema2MultiSelect$inboundSchema,
  Schema2Number,
  Schema2Number$inboundSchema,
  Schema2SingleSelect,
  Schema2SingleSelect$inboundSchema,
  Schema2Text,
  Schema2Text$inboundSchema,
  Schema2UnifiedKey6,
  Schema2UnifiedKey6$inboundSchema,
  Schema2UnifiedKey7,
  Schema2UnifiedKey7$inboundSchema,
} from "./schema2union1.js";

export type Schema2Object2 = {
  label: string;
  required: boolean;
  description?: string | null | undefined;
  unified_key?: Schema2UnifiedKey6 | null | undefined;
  type: "object";
  properties: { [k: string]: Schema1Union2 };
};

export type Schema2Union2 =
  | (Schema2SingleSelect & { type: "single_select" })
  | (Schema2MultiSelect & { type: "multi_select" })
  | (Schema2Object2 & { type: "object" })
  | (Schema2Array2 & { type: "array" })
  | (Schema2File & { type: "file" })
  | (Schema2Text & { type: "text" })
  | (Schema2Number & { type: "number" })
  | (Schema2Date & { type: "date" })
  | (Schema2Checkbox & { type: "checkbox" });

export type Schema2Array2 = {
  label: string;
  required: boolean;
  description?: string | null | undefined;
  unified_key?: Schema2UnifiedKey7 | null | undefined;
  type: "array";
  item_type:
    | (Schema2SingleSelect & { type: "single_select" })
    | (Schema2MultiSelect & { type: "multi_select" })
    | (Schema2Object2 & { type: "object" })
    | (Schema2Array2 & { type: "array" })
    | (Schema2File & { type: "file" })
    | (Schema2Text & { type: "text" })
    | (Schema2Number & { type: "number" })
    | (Schema2Date & { type: "date" })
    | (Schema2Checkbox & { type: "checkbox" });
  min_items?: number | null | undefined;
  max_items?: number | null | undefined;
};

/** @internal */
export const Schema2Object2$inboundSchema: z.ZodType<
  Schema2Object2,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: z.string(),
  required: z.boolean(),
  description: z.nullable(z.string()).optional(),
  unified_key: z.nullable(Schema2UnifiedKey6$inboundSchema).optional(),
  type: z.literal("object"),
  properties: z.record(z.lazy(() => Schema1Union2$inboundSchema)),
});

export function schema2Object2FromJSON(
  jsonString: string,
): SafeParseResult<Schema2Object2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schema2Object2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schema2Object2' from JSON`,
  );
}

/** @internal */
export const Schema2Union2$inboundSchema: z.ZodType<
  Schema2Union2,
  z.ZodTypeDef,
  unknown
> = z.union([
  Schema2SingleSelect$inboundSchema.and(
    z.object({ type: z.literal("single_select") }),
  ),
  Schema2MultiSelect$inboundSchema.and(
    z.object({ type: z.literal("multi_select") }),
  ),
  z.lazy(() => Schema2Object2$inboundSchema).and(
    z.object({ type: z.literal("object") }),
  ),
  z.lazy(() => Schema2Array2$inboundSchema).and(
    z.object({ type: z.literal("array") }),
  ),
  Schema2File$inboundSchema.and(z.object({ type: z.literal("file") })),
  Schema2Text$inboundSchema.and(z.object({ type: z.literal("text") })),
  Schema2Number$inboundSchema.and(z.object({ type: z.literal("number") })),
  Schema2Date$inboundSchema.and(z.object({ type: z.literal("date") })),
  Schema2Checkbox$inboundSchema.and(z.object({ type: z.literal("checkbox") })),
]);

export function schema2Union2FromJSON(
  jsonString: string,
): SafeParseResult<Schema2Union2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schema2Union2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schema2Union2' from JSON`,
  );
}

/** @internal */
export const Schema2Array2$inboundSchema: z.ZodType<
  Schema2Array2,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: z.string(),
  required: z.boolean(),
  description: z.nullable(z.string()).optional(),
  unified_key: z.nullable(Schema2UnifiedKey7$inboundSchema).optional(),
  type: z.literal("array"),
  item_type: z.union([
    Schema2SingleSelect$inboundSchema.and(
      z.object({ type: z.literal("single_select") }),
    ),
    Schema2MultiSelect$inboundSchema.and(
      z.object({ type: z.literal("multi_select") }),
    ),
    z.lazy(() => Schema2Object2$inboundSchema).and(
      z.object({ type: z.literal("object") }),
    ),
    z.lazy(() => Schema2Array2$inboundSchema).and(
      z.object({ type: z.literal("array") }),
    ),
    Schema2File$inboundSchema.and(z.object({ type: z.literal("file") })),
    Schema2Text$inboundSchema.and(z.object({ type: z.literal("text") })),
    Schema2Number$inboundSchema.and(z.object({ type: z.literal("number") })),
    Schema2Date$inboundSchema.and(z.object({ type: z.literal("date") })),
    Schema2Checkbox$inboundSchema.and(
      z.object({ type: z.literal("checkbox") }),
    ),
  ]),
  min_items: z.nullable(z.number()).optional(),
  max_items: z.nullable(z.number()).optional(),
});

export function schema2Array2FromJSON(
  jsonString: string,
): SafeParseResult<Schema2Array2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schema2Array2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schema2Array2' from JSON`,
  );
}
